// src/data/guide-bridge.ts — GENERATED by scripts/build-guide-bridge.mjs (2026-09-08). Do not edit.
//
// Phase 1A of PLAN_KNOWLEDGE_GRAPH_TO_VTA: each spellweb node that has a page in
// the guide carries that page's slug, so a constellation here projects onto the
// star chart by slug lookup — and a walk there evolves the same City Key as an
// inscription here. Identity is the slug, never the host: a fork of the page on
// another site is the SAME reference; `site` only says where the bake found it.
// `vertex` is the page's baked seat (its posture when it carries one, else its
// site strand's axis vertex); `postured` says which.
export const GUIDE_BRIDGE_RULE = 'identity is the slug, never the host';
export const GUIDE_BRIDGE_ORIGIN = 'https://guide.agentprivacy.ai/';
export interface GuideBridgeEntry { site: string; slug: string; vertex: number | null; postured: boolean }
export const GUIDE_BRIDGE: Record<string, GuideBridgeEntry> = {
 "concept-agentprivacy-mcp": {
  "site": "harness",
  "slug": "agentprivacy-mcp",
  "vertex": 2,
  "postured": false
 },
 "concept-swordsman-process": {
  "site": "harness",
  "slug": "the-swordsman-process",
  "vertex": 34,
  "postured": true
 },
 "concept-vta-record": {
  "site": "harness",
  "slug": "the-vta-record",
  "vertex": 41,
  "postured": true
 },
 "concept-page-posture": {
  "site": "guide",
  "slug": "page-posture",
  "vertex": 12,
  "postured": true
 },
 "concept-guide-bridge": {
  "site": "guide",
  "slug": "spellweb-guide-bridge",
  "vertex": 4,
  "postured": false
 },
 "concept-private-journey-bundle": {
  "site": "harness",
  "slug": "private-journey-bundle",
  "vertex": 2,
  "postured": false
 },
 "concept-agent-knowledge-space": {
  "site": "guide",
  "slug": "vta-star-knowledge-space",
  "vertex": 4,
  "postured": false
 },
 "concept-openvtc-vti": {
  "site": "harness",
  "slug": "openvtc-verifiable-trust-infrastructure",
  "vertex": 2,
  "postured": false
 },
 "concept-openvtc-vta-mcp": {
  "site": "harness",
  "slug": "openvtc-vta-mcp",
  "vertex": 2,
  "postured": false
 },
 "concept-vta-star-prototype": {
  "site": "guide",
  "slug": "vta-star-browser-prototype",
  "vertex": 4,
  "postured": false
 },
 "concept-star-presentation": {
  "site": "guide",
  "slug": "star-key-selected-presentation",
  "vertex": 4,
  "postured": false
 },
 "concept-star-core-artefact": {
  "site": "guide",
  "slug": "star-core-artefact-and-temporal-view",
  "vertex": 4,
  "postured": false
 },
 "concept-mages-city-runtime": {
  "site": "city",
  "slug": "mages-city-agent-knowledge-runtime",
  "vertex": 1,
  "postured": false
 },
 "concept-agentprivacy-labs": {
  "site": "research",
  "slug": "agentprivacy-labs",
  "vertex": 32,
  "postured": false
 },
 "concept-codex-mage": {
  "site": "codexmage",
  "slug": "codex-mage-research-continuity",
  "vertex": 4,
  "postured": false
 },
 "concept-harness-contribution-path": {
  "site": "harness",
  "slug": "harness-skills-and-adoption-evidence",
  "vertex": 2,
  "postured": false
 },
 "doc-dtg-zk-book": {
  "site": "dtg",
  "slug": "dtg-zk-book-evidence-bench",
  "vertex": 32,
  "postured": false
 },
 "doc-whitepaper": {
  "site": "atlas",
  "slug": "whitepaper-v47",
  "vertex": 8,
  "postured": false
 },
 "doc-research": {
  "site": "atlas",
  "slug": "research-paper-v35",
  "vertex": 8,
  "postured": false
 },
 "doc-glossary": {
  "site": "atlas",
  "slug": "glossary-master-v22",
  "vertex": 8,
  "postured": false
 },
 "doc-promise": {
  "site": "atlas",
  "slug": "promise-theory-reference-v10",
  "vertex": 8,
  "postured": false
 },
 "doc-visual": {
  "site": "atlas",
  "slug": "visual-architecture-guide-v12",
  "vertex": 8,
  "postured": false
 },
 "doc-tokenomics": {
  "site": "atlas",
  "slug": "vrc-protocol-economics-v30",
  "vertex": 8,
  "postured": false
 },
 "doc-zypher": {
  "site": "atlas",
  "slug": "understanding-as-key-v10",
  "vertex": 8,
  "postured": false
 },
 "doc-emissary-poem": {
  "site": "atlas",
  "slug": "the-emissary-who-forgot-the-master",
  "vertex": 8,
  "postured": false
 },
 "doc-amnesia-poems": {
  "site": "atlas",
  "slug": "the-amnesia-protocol-poems",
  "vertex": 8,
  "postured": false
 },
 "doc-tide-selene-poem": {
  "site": "atlas",
  "slug": "the-tide-proves-orbit-keeps-selene",
  "vertex": 8,
  "postured": false
 },
 "doc-what-agentprivacy-is": {
  "site": "atlas",
  "slug": "what-agentprivacy-is",
  "vertex": 8,
  "postured": false
 },
 "doc-systems-hexagram": {
  "site": "atlas",
  "slug": "systems-hexagram-physics-v12",
  "vertex": 8,
  "postured": false
 },
 "doc-dual-territory-ceremony": {
  "site": "atlas",
  "slug": "dual-territory-ceremony-spec-v10",
  "vertex": 8,
  "postured": false
 },
 "doc-zk-blade-forge": {
  "site": "atlas",
  "slug": "zk-swordsman-blade-forge-v30-narrative",
  "vertex": 8,
  "postured": false
 },
 "doc-privacy-value-v5": {
  "site": "atlas",
  "slug": "privacy-is-value-v5",
  "vertex": 8,
  "postured": false
 },
 "doc-privacy-value-v6": {
  "site": "atlas",
  "slug": "privacy-value-model-v6",
  "vertex": 8,
  "postured": false
 },
 "doc-celestial-ceremonies": {
  "site": "atlas",
  "slug": "the-celestial-dual-ceremony",
  "vertex": 8,
  "postured": false
 },
 "doc-celestial-key-guide": {
  "site": "atlas",
  "slug": "celestial-key-ceremony-guide",
  "vertex": 8,
  "postured": false
 },
 "doc-forging-celestial-overlap": {
  "site": "atlas",
  "slug": "forging-the-celestial-overlap",
  "vertex": 8,
  "postured": false
 },
 "doc-blade-pathway": {
  "site": "atlas",
  "slug": "celestial-ceremony-blade-pathway",
  "vertex": 8,
  "postured": false
 },
 "doc-zk-blade-forge-spec": {
  "site": "atlas",
  "slug": "zk-blades-forge-specification-v101",
  "vertex": 8,
  "postured": false
 },
 "doc-moon-phase-notation": {
  "site": "atlas",
  "slug": "moon-phase-notation-spec",
  "vertex": 8,
  "postured": false
 },
 "doc-privacymage-grimoire-v10-2": {
  "site": "atlas",
  "slug": "privacymage-grimoire-v1021",
  "vertex": 8,
  "postured": false
 },
 "doc-privacymage-grimoire-v10-4": {
  "site": "atlas",
  "slug": "privacymage-grimoire-v1040",
  "vertex": 8,
  "postured": false
 },
 "doc-myterms-alliance-application": {
  "site": "atlas",
  "slug": "myterms-alliance-founding-member-application",
  "vertex": 8,
  "postured": false
 },
 "doc-ieee7012-integration-plan": {
  "site": "atlas",
  "slug": "ieee-7012-integration-plan-v2",
  "vertex": 8,
  "postured": false
 },
 "doc-privacy-is-value-equation": {
  "site": "atlas",
  "slug": "privacy-is-value-equation-explainer-myterms",
  "vertex": 8,
  "postured": false
 },
 "spellbook-firstperson": {
  "site": "atlas",
  "slug": "first-person-spellbook",
  "vertex": 8,
  "postured": false
 },
 "fp-act-1": {
  "site": "atlas",
  "slug": "act-1-venice-1494",
  "vertex": 8,
  "postured": false
 },
 "fp-act-2": {
  "site": "atlas",
  "slug": "act-2-dual-ceremony",
  "vertex": 8,
  "postured": false
 },
 "fp-act-3": {
  "site": "atlas",
  "slug": "act-3-drakes-teaching",
  "vertex": 8,
  "postured": false
 },
 "fp-act-4": {
  "site": "atlas",
  "slug": "act-4-blade-alone",
  "vertex": 8,
  "postured": false
 },
 "fp-act-5": {
  "site": "atlas",
  "slug": "act-5-light-armor",
  "vertex": 8,
  "postured": false
 },
 "fp-act-6": {
  "site": "atlas",
  "slug": "act-6-trust-graph-plane",
  "vertex": 8,
  "postured": false
 },
 "fp-act-7": {
  "site": "atlas",
  "slug": "act-7-the-anti-mirror",
  "vertex": 8,
  "postured": false
 },
 "fp-act-8": {
  "site": "atlas",
  "slug": "act-8-ancient-rule",
  "vertex": 8,
  "postured": false
 },
 "fp-act-9": {
  "site": "atlas",
  "slug": "act-9-zcash-shield",
  "vertex": 8,
  "postured": false
 },
 "fp-act-10": {
  "site": "atlas",
  "slug": "act-10-triangle-geometry",
  "vertex": 8,
  "postured": false
 },
 "fp-act-11": {
  "site": "atlas",
  "slug": "act-11-golden-ratio",
  "vertex": 8,
  "postured": false
 },
 "fp-act-12": {
  "site": "atlas",
  "slug": "act-12-the-forgetting",
  "vertex": 8,
  "postured": false
 },
 "fp-act-13": {
  "site": "atlas",
  "slug": "act-13-book-of-promises",
  "vertex": 8,
  "postured": false
 },
 "fp-act-14": {
  "site": "atlas",
  "slug": "act-14-claimed-string",
  "vertex": 8,
  "postured": false
 },
 "fp-act-15": {
  "site": "atlas",
  "slug": "act-15-running-in-shackles",
  "vertex": 8,
  "postured": false
 },
 "fp-act-16": {
  "site": "atlas",
  "slug": "act-16-pools-become-wells",
  "vertex": 8,
  "postured": false
 },
 "fp-act-17": {
  "site": "atlas",
  "slug": "act-17-bonfire-in-dark-forest",
  "vertex": 8,
  "postured": false
 },
 "fp-act-18": {
  "site": "atlas",
  "slug": "act-18-mirror-in-dust",
  "vertex": 8,
  "postured": false
 },
 "fp-act-19": {
  "site": "atlas",
  "slug": "act-19-anthropic-archivist",
  "vertex": 8,
  "postured": false
 },
 "fp-act-20": {
  "site": "atlas",
  "slug": "act-20-infinite-vault",
  "vertex": 8,
  "postured": false
 },
 "fp-act-21": {
  "site": "atlas",
  "slug": "act-21-hitchhikers-gambit",
  "vertex": 8,
  "postured": false
 },
 "fp-act-22": {
  "site": "atlas",
  "slug": "act-22-hoopy-frood",
  "vertex": 8,
  "postured": false
 },
 "fp-act-23": {
  "site": "atlas",
  "slug": "act-23-manifold-dragon",
  "vertex": 8,
  "postured": false
 },
 "fp-act-24": {
  "site": "atlas",
  "slug": "act-24-holographic-bound",
  "vertex": 8,
  "postured": false
 },
 "fp-act-25": {
  "site": "atlas",
  "slug": "act-25-the-dragons-hide",
  "vertex": 8,
  "postured": false
 },
 "fp-act-26": {
  "site": "atlas",
  "slug": "act-26-master-and-emissary",
  "vertex": 8,
  "postured": false
 },
 "fp-act-27": {
  "site": "atlas",
  "slug": "act-27-forging-zero-knowledge-blades",
  "vertex": 8,
  "postured": false
 },
 "fp-act-28": {
  "site": "atlas",
  "slug": "act-28-the-celestial-ceremony-engine",
  "vertex": 8,
  "postured": false
 },
 "fp-act-29": {
  "site": "atlas",
  "slug": "act-29-the-dragon-wakes",
  "vertex": 8,
  "postured": false
 },
 "fp-act-30": {
  "site": "atlas",
  "slug": "act-30-the-dihedral-mirror",
  "vertex": 8,
  "postured": false
 },
 "fp-act-31": {
  "site": "atlas",
  "slug": "act-31-the-first-delegation",
  "vertex": 8,
  "postured": false
 },
 "spellbook-zk": {
  "site": "atlas",
  "slug": "zero-knowledge-spellbook-v20",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-1": {
  "site": "atlas",
  "slug": "zk-tale-1-monastery",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-2": {
  "site": "atlas",
  "slug": "zk-tale-2-three-trials",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-3": {
  "site": "atlas",
  "slug": "zk-tale-3-silent-messenger",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-4": {
  "site": "atlas",
  "slug": "zk-tale-4-finite-fields",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-5": {
  "site": "atlas",
  "slug": "zk-tale-5-constraint-forge",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-6": {
  "site": "atlas",
  "slug": "zk-tale-6-polynomial-riddle",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-8": {
  "site": "atlas",
  "slug": "zk-tale-8-plonkish-revolution",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-9": {
  "site": "atlas",
  "slug": "zk-tale-9-pairing-dance",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-10": {
  "site": "atlas",
  "slug": "zk-tale-10-commitment-ceremony",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-11": {
  "site": "atlas",
  "slug": "zk-tale-11-fri-oracle",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-12": {
  "site": "atlas",
  "slug": "zk-tale-12-folding-path",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-13": {
  "site": "atlas",
  "slug": "zk-tale-13-sumcheck-riddle",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-14": {
  "site": "atlas",
  "slug": "zk-tale-14-ipa-chronicle",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-15": {
  "site": "atlas",
  "slug": "zk-tale-15-mirror-within-mirrors",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-16": {
  "site": "atlas",
  "slug": "zk-tale-16-cyclic-ceremony",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-17": {
  "site": "atlas",
  "slug": "zk-tale-17-universal-setup",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-18": {
  "site": "atlas",
  "slug": "zk-tale-18-toxic-waste-dragon",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-19": {
  "site": "atlas",
  "slug": "zk-tale-19-zkvm-kingdom",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-20": {
  "site": "atlas",
  "slug": "zk-tale-20-cairo-scribes",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-21": {
  "site": "atlas",
  "slug": "zk-tale-21-circom-workshops",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-22": {
  "site": "atlas",
  "slug": "zk-tale-22-zkevm-empire",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-23": {
  "site": "atlas",
  "slug": "zk-tale-23-private-coin-of-zcash",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-24": {
  "site": "atlas",
  "slug": "zk-tale-24-tornados-eye",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-25": {
  "site": "atlas",
  "slug": "zk-tale-25-rollup-realms",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-26": {
  "site": "atlas",
  "slug": "zk-tale-26-vulnerability-codex",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-27": {
  "site": "atlas",
  "slug": "zk-tale-27-data-availability-prophecy",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-28": {
  "site": "atlas",
  "slug": "zk-tale-28-bridge-between-worlds",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-29": {
  "site": "atlas",
  "slug": "zk-tale-29-intelligence-proof",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-30": {
  "site": "atlas",
  "slug": "zk-tale-30-eternal-sovereignty",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-31": {
  "site": "atlas",
  "slug": "zk-tale-31-naming-of-the-unnamed",
  "vertex": 8,
  "postured": false
 },
 "zk-tale-32": {
  "site": "atlas",
  "slug": "zk-tale-32-the-flock",
  "vertex": 8,
  "postured": false
 },
 "spellbook-canon": {
  "site": "atlas",
  "slug": "blockchain-canon",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-0": {
  "site": "atlas",
  "slug": "canon-ch-0-preface",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-1": {
  "site": "atlas",
  "slug": "canon-ch-1-cypherpunk-whispers",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-2": {
  "site": "atlas",
  "slug": "canon-ch-2-early-incantations",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-3": {
  "site": "atlas",
  "slug": "canon-ch-3-the-synthesis",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-4": {
  "site": "atlas",
  "slug": "canon-ch-4-world-computer",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-5": {
  "site": "atlas",
  "slug": "canon-ch-5-first-fracture",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-6": {
  "site": "atlas",
  "slug": "canon-ch-6-great-schism",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-7": {
  "site": "atlas",
  "slug": "canon-ch-7-surveillance-truth",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-8": {
  "site": "atlas",
  "slug": "canon-ch-8-missing-primitive",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-9": {
  "site": "atlas",
  "slug": "canon-ch-9-open-canon",
  "vertex": 8,
  "postured": false
 },
 "canon-ch-10": {
  "site": "atlas",
  "slug": "canon-ch-10-timeline",
  "vertex": 8,
  "postured": false
 },
 "spellbook-parallel": {
  "site": "atlas",
  "slug": "parallel-society-spellbook",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-1": {
  "site": "atlas",
  "slug": "ps-ch-1-peace-became-prison",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-2": {
  "site": "atlas",
  "slug": "ps-ch-2-rusted-crowns",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-3": {
  "site": "atlas",
  "slug": "ps-ch-3-cambrian-garden",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-4": {
  "site": "atlas",
  "slug": "ps-ch-4-cypherpunk-prophecies",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-5": {
  "site": "atlas",
  "slug": "ps-ch-5-drakes-deeper-teaching",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-6": {
  "site": "atlas",
  "slug": "ps-ch-6-arsenal-and-grimoire",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-7": {
  "site": "atlas",
  "slug": "ps-ch-7-corruption-crypto-cures",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-8": {
  "site": "atlas",
  "slug": "ps-ch-8-cyberstate-question",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-9": {
  "site": "atlas",
  "slug": "ps-ch-9-exit-exile-access",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-10": {
  "site": "atlas",
  "slug": "ps-ch-10-rethinking-sovereignty",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-12": {
  "site": "atlas",
  "slug": "ps-ch-12-community-collaboration",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-13": {
  "site": "atlas",
  "slug": "ps-ch-13-community-conflict",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-14": {
  "site": "atlas",
  "slug": "ps-ch-14-deep-technology",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-15": {
  "site": "atlas",
  "slug": "ps-ch-15-conceptual-limits",
  "vertex": 8,
  "postured": false
 },
 "ps-ch-16": {
  "site": "atlas",
  "slug": "ps-ch-16-inevitable-communities",
  "vertex": 8,
  "postured": false
 },
 "spellbook-plurality": {
  "site": "atlas",
  "slug": "plurality-spellbook",
  "vertex": 8,
  "postured": false
 },
 "pl-act-1": {
  "site": "atlas",
  "slug": "act-i-first-overlap",
  "vertex": 8,
  "postured": false
 },
 "pl-act-2": {
  "site": "atlas",
  "slug": "act-ii-widening-gulf",
  "vertex": 8,
  "postured": false
 },
 "pl-act-3": {
  "site": "atlas",
  "slug": "act-iii-view-from-yushan",
  "vertex": 8,
  "postured": false
 },
 "pl-act-4": {
  "site": "atlas",
  "slug": "act-iv-digital-democracy",
  "vertex": 8,
  "postured": false
 },
 "pl-act-5": {
  "site": "atlas",
  "slug": "act-v-glyph-that-breathes",
  "vertex": 8,
  "postured": false
 },
 "pl-act-6": {
  "site": "atlas",
  "slug": "act-vi-web-beneath-web",
  "vertex": 8,
  "postured": false
 },
 "pl-act-7": {
  "site": "atlas",
  "slug": "act-vii-teachers-before-drake",
  "vertex": 8,
  "postured": false
 },
 "pl-act-8": {
  "site": "atlas",
  "slug": "act-viii-path-abandoned",
  "vertex": 8,
  "postured": false
 },
 "pl-act-9": {
  "site": "atlas",
  "slug": "act-ix-foundation-floor",
  "vertex": 8,
  "postured": false
 },
 "pl-act-10": {
  "site": "atlas",
  "slug": "act-x-name-yourself",
  "vertex": 8,
  "postured": false
 },
 "pl-act-11": {
  "site": "atlas",
  "slug": "act-xi-self-forming-guilds",
  "vertex": 8,
  "postured": false
 },
 "pl-act-12": {
  "site": "atlas",
  "slug": "act-xii-market-doesnt-devour",
  "vertex": 8,
  "postured": false
 },
 "pl-act-13": {
  "site": "atlas",
  "slug": "act-xiii-held-together",
  "vertex": 8,
  "postured": false
 },
 "pl-act-14": {
  "site": "atlas",
  "slug": "act-xiv-door-both-ways",
  "vertex": 8,
  "postured": false
 },
 "pl-act-15": {
  "site": "atlas",
  "slug": "act-xv-words-before-words",
  "vertex": 8,
  "postured": false
 },
 "pl-act-16": {
  "site": "atlas",
  "slug": "act-xvi-world-we-build",
  "vertex": 8,
  "postured": false
 },
 "pl-act-17": {
  "site": "atlas",
  "slug": "act-xvii-creation-compounds",
  "vertex": 8,
  "postured": false
 },
 "pl-act-18": {
  "site": "atlas",
  "slug": "act-xviii-hearing-at-scale",
  "vertex": 8,
  "postured": false
 },
 "pl-act-19": {
  "site": "atlas",
  "slug": "act-xix-rules-that-learn",
  "vertex": 8,
  "postured": false
 },
 "pl-act-20": {
  "site": "atlas",
  "slug": "act-xx-weight-of-wanting",
  "vertex": 8,
  "postured": false
 },
 "pl-act-21": {
  "site": "atlas",
  "slug": "act-xxi-market-remembers",
  "vertex": 8,
  "postured": false
 },
 "pl-act-22": {
  "site": "atlas",
  "slug": "act-xxii-circle-includes",
  "vertex": 8,
  "postured": false
 },
 "pl-act-23": {
  "site": "atlas",
  "slug": "act-xxiii-forge-of-peers",
  "vertex": 8,
  "postured": false
 },
 "pl-act-24": {
  "site": "atlas",
  "slug": "act-xxiv-bodys-secrets",
  "vertex": 8,
  "postured": false
 },
 "pl-act-25": {
  "site": "atlas",
  "slug": "act-xxv-signal-and-noise",
  "vertex": 8,
  "postured": false
 },
 "pl-act-26": {
  "site": "atlas",
  "slug": "act-xxvi-commons-breathes",
  "vertex": 8,
  "postured": false
 },
 "pl-act-27": {
  "site": "atlas",
  "slug": "act-xxvii-mind-that-grows",
  "vertex": 8,
  "postured": false
 },
 "pl-act-28": {
  "site": "atlas",
  "slug": "act-xxviii-laws-enable",
  "vertex": 8,
  "postured": false
 },
 "pl-act-29": {
  "site": "atlas",
  "slug": "act-xxix-window-closes",
  "vertex": 8,
  "postured": false
 },
 "pl-act-30": {
  "site": "atlas",
  "slug": "act-xxx-ceremony-complete",
  "vertex": 8,
  "postured": false
 },
 "per-soulbis": {
  "site": "skill",
  "slug": "soulbis",
  "vertex": 16,
  "postured": false
 },
 "per-soulbae": {
  "site": "skill",
  "slug": "soulbae",
  "vertex": 16,
  "postured": false
 },
 "per-cipher": {
  "site": "atlas",
  "slug": "cipher",
  "vertex": 8,
  "postured": false
 },
 "per-warden": {
  "site": "atlas",
  "slug": "warden",
  "vertex": 8,
  "postured": false
 },
 "per-gatekeeper": {
  "site": "atlas",
  "slug": "gatekeeper",
  "vertex": 8,
  "postured": false
 },
 "per-ranger": {
  "site": "atlas",
  "slug": "ranger",
  "vertex": 8,
  "postured": false
 },
 "per-sentinel": {
  "site": "atlas",
  "slug": "sentinel",
  "vertex": 8,
  "postured": false
 },
 "per-assessor": {
  "site": "skill",
  "slug": "assessor",
  "vertex": 16,
  "postured": false
 },
 "per-ambassador": {
  "site": "atlas",
  "slug": "ambassador",
  "vertex": 8,
  "postured": false
 },
 "per-chronicler": {
  "site": "skill",
  "slug": "chronicler",
  "vertex": 16,
  "postured": false
 },
 "per-shipwright": {
  "site": "skill",
  "slug": "shipwright",
  "vertex": 16,
  "postured": false
 },
 "per-weaver": {
  "site": "atlas",
  "slug": "weaver",
  "vertex": 8,
  "postured": false
 },
 "per-healer": {
  "site": "atlas",
  "slug": "healer",
  "vertex": 8,
  "postured": false
 },
 "per-witness": {
  "site": "atlas",
  "slug": "witness",
  "vertex": 8,
  "postured": false
 },
 "per-architect": {
  "site": "atlas",
  "slug": "architect",
  "vertex": 8,
  "postured": false
 },
 "per-pedagogue": {
  "site": "atlas",
  "slug": "pedagogue",
  "vertex": 8,
  "postured": false
 },
 "per-algebraist": {
  "site": "atlas",
  "slug": "algebraist",
  "vertex": 8,
  "postured": false
 },
 "per-topologist": {
  "site": "atlas",
  "slug": "topologist",
  "vertex": 8,
  "postured": false
 },
 "per-stranger-witness": {
  "site": "atlas",
  "slug": "stranger-witness",
  "vertex": 8,
  "postured": false
 },
 "per-drake": {
  "site": "atlas",
  "slug": "the-drake",
  "vertex": 8,
  "postured": false
 },
 "con-paradox": {
  "site": "atlas",
  "slug": "privacy-delegation-paradox",
  "vertex": 8,
  "postured": false
 },
 "con-dualagent": {
  "site": "atlas",
  "slug": "dual-agent-architecture",
  "vertex": 8,
  "postured": false
 },
 "con-7thcapital": {
  "site": "atlas",
  "slug": "7th-capital",
  "vertex": 8,
  "postured": false
 },
 "con-gap": {
  "site": "atlas",
  "slug": "the-gap",
  "vertex": 8,
  "postured": false
 },
 "con-separation": {
  "site": "atlas",
  "slug": "conditional-independence",
  "vertex": 8,
  "postured": false
 },
 "con-vrc": {
  "site": "atlas",
  "slug": "vrc",
  "vertex": 8,
  "postured": false
 },
 "con-rpp": {
  "site": "atlas",
  "slug": "relationship-proverb-protocol",
  "vertex": 8,
  "postured": false
 },
 "con-promisetheory": {
  "site": "atlas",
  "slug": "promise-theory",
  "vertex": 8,
  "postured": false
 },
 "con-trusttiers": {
  "site": "atlas",
  "slug": "progressive-trust-tiers",
  "vertex": 8,
  "postured": false
 },
 "con-zkproofs": {
  "site": "atlas",
  "slug": "zero-knowledge-proofs",
  "vertex": 8,
  "postured": false
 },
 "con-privacypools": {
  "site": "atlas",
  "slug": "privacy-pools",
  "vertex": 8,
  "postured": false
 },
 "con-surveillance": {
  "site": "atlas",
  "slug": "surveillance-capitalism",
  "vertex": 8,
  "postured": false
 },
 "con-plurality": {
  "site": "atlas",
  "slug": "plurality",
  "vertex": 8,
  "postured": false
 },
 "con-quadratic": {
  "site": "atlas",
  "slug": "quadratic-mechanisms",
  "vertex": 8,
  "postured": false
 },
 "con-westphalia": {
  "site": "atlas",
  "slug": "westphalia-1648",
  "vertex": 8,
  "postured": false
 },
 "con-dihedral": {
  "site": "atlas",
  "slug": "dihedral-sovereignty-d",
  "vertex": 8,
  "postured": false
 },
 "con-ring-algebra": {
  "site": "atlas",
  "slug": "ring-algebra-z2z",
  "vertex": 8,
  "postured": false
 },
 "con-content-addressing": {
  "site": "atlas",
  "slug": "content-addressing",
  "vertex": 8,
  "postured": false
 },
 "con-understanding-as-key": {
  "site": "guide",
  "slug": "understanding-as-key",
  "vertex": 4,
  "postured": false
 },
 "con-emissary-recursion": {
  "site": "atlas",
  "slug": "emissary-recursion",
  "vertex": 8,
  "postured": false
 },
 "con-serenity-kernel": {
  "site": "atlas",
  "slug": "serenity-kernel",
  "vertex": 8,
  "postured": false
 },
 "con-atlas-resonance": {
  "site": "atlas",
  "slug": "atlas-of-resonance-classes",
  "vertex": 8,
  "postured": false
 },
 "con-prism-spectrum": {
  "site": "atlas",
  "slug": "prism-spectrum",
  "vertex": 8,
  "postured": false
 },
 "thm-separation": {
  "site": "atlas",
  "slug": "separation-theorem",
  "vertex": 8,
  "postured": false
 },
 "thm-ceiling": {
  "site": "atlas",
  "slug": "reconstruction-ceiling",
  "vertex": 8,
  "postured": false
 },
 "thm-errfloor": {
  "site": "atlas",
  "slug": "error-floor-theorem",
  "vertex": 8,
  "postured": false
 },
 "thm-degradation": {
  "site": "atlas",
  "slug": "graceful-degradation",
  "vertex": 8,
  "postured": false
 },
 "spell-master": {
  "site": "atlas",
  "slug": "master-inscription",
  "vertex": 8,
  "postured": false
 },
 "spell-vrc": {
  "site": "atlas",
  "slug": "vrc-formation",
  "vertex": 8,
  "postured": false
 },
 "spell-ceremony": {
  "site": "atlas",
  "slug": "genesis-ceremony",
  "vertex": 8,
  "postured": false
 },
 "spell-dragon": {
  "site": "atlas",
  "slug": "dragon-emergence",
  "vertex": 8,
  "postured": false
 },
 "spell-gap": {
  "site": "atlas",
  "slug": "the-gap-spell",
  "vertex": 8,
  "postured": false
 },
 "spell-weather": {
  "site": "atlas",
  "slug": "building-weather",
  "vertex": 8,
  "postured": false
 },
 "spell-spellweb": {
  "site": "atlas",
  "slug": "spellweb",
  "vertex": 8,
  "postured": false
 },
 "spell-plurality": {
  "site": "atlas",
  "slug": "plurality-spell",
  "vertex": 8,
  "postured": false
 },
 "spell-emissary-recursion": {
  "site": "atlas",
  "slug": "emissary-recursion",
  "vertex": 8,
  "postured": false
 },
 "spell-symphony-within": {
  "site": "atlas",
  "slug": "the-symphony-within",
  "vertex": 8,
  "postured": false
 },
 "spell-dihedral-door": {
  "site": "atlas",
  "slug": "two-mirrors-make-a-door",
  "vertex": 8,
  "postured": false
 },
 "spell-sun-ceremony": {
  "site": "atlas",
  "slug": "sun-ceremony",
  "vertex": 8,
  "postured": false
 },
 "spell-moon-ceremony": {
  "site": "atlas",
  "slug": "moon-ceremony",
  "vertex": 8,
  "postured": false
 },
 "spell-aether-ceremony": {
  "site": "atlas",
  "slug": "aether-ceremony",
  "vertex": 8,
  "postured": false
 },
 "spell-celestial-key": {
  "site": "atlas",
  "slug": "celestial-key",
  "vertex": 8,
  "postured": false
 },
 "spell-sun-blade": {
  "site": "atlas",
  "slug": "sun-blade-inscription",
  "vertex": 8,
  "postured": false
 },
 "spell-moon-blade": {
  "site": "atlas",
  "slug": "moon-blade-inscription",
  "vertex": 8,
  "postured": false
 },
 "spell-paired-inscription": {
  "site": "atlas",
  "slug": "paired-blade-inscription",
  "vertex": 8,
  "postured": false
 },
 "skill-crypto-zkp": {
  "site": "atlas",
  "slug": "crypto-zkp",
  "vertex": 8,
  "postured": false
 },
 "skill-browser": {
  "site": "atlas",
  "slug": "browser-privacy",
  "vertex": 8,
  "postured": false
 },
 "skill-darkforest": {
  "site": "atlas",
  "slug": "dark-forest",
  "vertex": 8,
  "postured": false
 },
 "skill-academic": {
  "site": "atlas",
  "slug": "academic-research",
  "vertex": 8,
  "postured": false
 },
 "skill-boundary": {
  "site": "atlas",
  "slug": "boundary-enforcement",
  "vertex": 8,
  "postured": false
 },
 "skill-selective": {
  "site": "atlas",
  "slug": "selective-disclosure",
  "vertex": 8,
  "postured": false
 },
 "skill-nullifier": {
  "site": "atlas",
  "slug": "nullifier-design",
  "vertex": 8,
  "postured": false
 },
 "skill-metadata": {
  "site": "atlas",
  "slug": "metadata-resistance",
  "vertex": 8,
  "postured": false
 },
 "skill-perimeter": {
  "site": "atlas",
  "slug": "perimeter-hardening",
  "vertex": 8,
  "postured": false
 },
 "skill-forensic": {
  "site": "atlas",
  "slug": "forensic-defense",
  "vertex": 8,
  "postured": false
 },
 "skill-enclave": {
  "site": "atlas",
  "slug": "enclave-operations",
  "vertex": 8,
  "postured": false
 },
 "skill-revocation": {
  "site": "atlas",
  "slug": "revocation-mechanics",
  "vertex": 8,
  "postured": false
 },
 "skill-threat": {
  "site": "atlas",
  "slug": "threat-adversarial",
  "vertex": 8,
  "postured": false
 },
 "skill-economics": {
  "site": "atlas",
  "slug": "privacy-economics",
  "vertex": 8,
  "postured": false
 },
 "skill-governance": {
  "site": "atlas",
  "slug": "policy-governance",
  "vertex": 8,
  "postured": false
 },
 "skill-narrative": {
  "site": "atlas",
  "slug": "narrative-compression",
  "vertex": 8,
  "postured": false
 },
 "skill-plurality": {
  "site": "atlas",
  "slug": "plurality-cooperative",
  "vertex": 8,
  "postured": false
 },
 "skill-aiagent": {
  "site": "atlas",
  "slug": "ai-agent-design",
  "vertex": 8,
  "postured": false
 },
 "skill-hitchhiker": {
  "site": "atlas",
  "slug": "hitchhiker-governance",
  "vertex": 8,
  "postured": false
 },
 "skill-grimoire": {
  "site": "atlas",
  "slug": "grimoire-navigation",
  "vertex": 8,
  "postured": false
 },
 "skill-proverbiogenesis": {
  "site": "atlas",
  "slug": "proverbiogenesis",
  "vertex": 8,
  "postured": false
 },
 "skill-spell-encoding": {
  "site": "atlas",
  "slug": "spell-encoding",
  "vertex": 8,
  "postured": false
 },
 "skill-inscription": {
  "site": "atlas",
  "slug": "inscription-mechanics",
  "vertex": 8,
  "postured": false
 },
 "skill-reputation": {
  "site": "atlas",
  "slug": "reputation-credentials",
  "vertex": 8,
  "postured": false
 },
 "skill-cross-chain": {
  "site": "atlas",
  "slug": "cross-chain",
  "vertex": 8,
  "postured": false
 },
 "skill-agent-interop": {
  "site": "atlas",
  "slug": "agent-interop",
  "vertex": 8,
  "postured": false
 },
 "skill-armor-progression": {
  "site": "atlas",
  "slug": "armor-progression",
  "vertex": 8,
  "postured": false
 },
 "skill-consent": {
  "site": "atlas",
  "slug": "consent-infrastructure",
  "vertex": 8,
  "postured": false
 },
 "skill-constellation": {
  "site": "atlas",
  "slug": "constellation-method",
  "vertex": 8,
  "postured": false
 },
 "skill-intel-pooling": {
  "site": "atlas",
  "slug": "intel-pooling",
  "vertex": 8,
  "postured": false
 },
 "skill-key-ceremony": {
  "site": "atlas",
  "slug": "key-ceremony",
  "vertex": 8,
  "postured": false
 },
 "skill-recovery-rpp": {
  "site": "atlas",
  "slug": "recovery-rpp",
  "vertex": 8,
  "postured": false
 },
 "skill-separation": {
  "site": "atlas",
  "slug": "separation-enforcement",
  "vertex": 8,
  "postured": false
 },
 "skill-sovereignty-econ": {
  "site": "atlas",
  "slug": "sovereignty-economics",
  "vertex": 8,
  "postured": false
 },
 "skill-story-diffusion": {
  "site": "atlas",
  "slug": "story-diffusion",
  "vertex": 8,
  "postured": false
 },
 "skill-trust-spanning": {
  "site": "atlas",
  "slug": "trust-spanning",
  "vertex": 8,
  "postured": false
 },
 "skill-understanding-key": {
  "site": "guide",
  "slug": "understanding-as-key",
  "vertex": 4,
  "postured": false
 },
 "skill-governance-agents": {
  "site": "atlas",
  "slug": "governance-agents",
  "vertex": 8,
  "postured": false
 },
 "skill-data-dignity": {
  "site": "atlas",
  "slug": "data-dignity",
  "vertex": 8,
  "postured": false
 },
 "skill-dragon": {
  "site": "atlas",
  "slug": "dragon-skill",
  "vertex": 8,
  "postured": false
 },
 "skill-vrc-identity": {
  "site": "atlas",
  "slug": "vrc-identity",
  "vertex": 8,
  "postured": false
 },
 "skill-promise-theory": {
  "site": "atlas",
  "slug": "promise-theory",
  "vertex": 8,
  "postured": false
 },
 "skill-knowledgegraph": {
  "site": "atlas",
  "slug": "knowledge-graph",
  "vertex": 8,
  "postured": false
 },
 "skill-tetrahedral": {
  "site": "atlas",
  "slug": "tetrahedral-sovereignty",
  "vertex": 8,
  "postured": false
 },
 "skill-uor-toroidal": {
  "site": "atlas",
  "slug": "uor-toroidal",
  "vertex": 8,
  "postured": false
 },
 "skill-edge-value": {
  "site": "atlas",
  "slug": "edge-value",
  "vertex": 8,
  "postured": false
 },
 "skill-network-topology": {
  "site": "atlas",
  "slug": "network-topology",
  "vertex": 8,
  "postured": false
 },
 "skill-temporal": {
  "site": "atlas",
  "slug": "temporal-dynamics",
  "vertex": 8,
  "postured": false
 },
 "proto-x402": {
  "site": "atlas",
  "slug": "x402-http-payments",
  "vertex": 8,
  "postured": false
 },
 "proto-vrc": {
  "site": "atlas",
  "slug": "vrc-protocol",
  "vertex": 8,
  "postured": false
 },
 "proto-rpp": {
  "site": "atlas",
  "slug": "rpp-protocol",
  "vertex": 8,
  "postured": false
 },
 "std-erc-8004": {
  "site": "atlas",
  "slug": "erc-8004-agent-identity",
  "vertex": 8,
  "postured": false
 },
 "std-erc-7812": {
  "site": "atlas",
  "slug": "erc-7812-zk-commitments",
  "vertex": 8,
  "postured": false
 },
 "std-did": {
  "site": "atlas",
  "slug": "dids-w3c",
  "vertex": 8,
  "postured": false
 },
 "std-vc": {
  "site": "atlas",
  "slug": "verifiable-credentials",
  "vertex": 8,
  "postured": false
 },
 "std-groth16": {
  "site": "atlas",
  "slug": "groth16",
  "vertex": 8,
  "postured": false
 },
 "std-plonk": {
  "site": "atlas",
  "slug": "plonk",
  "vertex": 8,
  "postured": false
 },
 "std-stark": {
  "site": "atlas",
  "slug": "stark",
  "vertex": 8,
  "postured": false
 },
 "std-nova": {
  "site": "atlas",
  "slug": "nova",
  "vertex": 8,
  "postured": false
 },
 "std-halo": {
  "site": "atlas",
  "slug": "halo",
  "vertex": 8,
  "postured": false
 },
 "person-chaum": {
  "site": "atlas",
  "slug": "david-chaum",
  "vertex": 8,
  "postured": false
 },
 "person-satoshi": {
  "site": "atlas",
  "slug": "satoshi-nakamoto",
  "vertex": 8,
  "postured": false
 },
 "person-vitalik": {
  "site": "atlas",
  "slug": "vitalik-buterin",
  "vertex": 8,
  "postured": false
 },
 "person-audrey": {
  "site": "atlas",
  "slug": "audrey-tang",
  "vertex": 8,
  "postured": false
 },
 "person-weyl": {
  "site": "atlas",
  "slug": "glen-weyl",
  "vertex": 8,
  "postured": false
 },
 "tech-zcash": {
  "site": "atlas",
  "slug": "zcash",
  "vertex": 8,
  "postured": false
 },
 "tech-ethereum": {
  "site": "atlas",
  "slug": "ethereum",
  "vertex": 8,
  "postured": false
 },
 "tech-nillion": {
  "site": "atlas",
  "slug": "nillion",
  "vertex": 8,
  "postured": false
 },
 "tech-polis": {
  "site": "atlas",
  "slug": "polis",
  "vertex": 8,
  "postured": false
 },
 "org-bgin": {
  "site": "atlas",
  "slug": "bgin",
  "vertex": 8,
  "postured": false
 },
 "org-toip": {
  "site": "atlas",
  "slug": "trust-over-ip",
  "vertex": 8,
  "postured": false
 },
 "org-iiw": {
  "site": "atlas",
  "slug": "iiw",
  "vertex": 8,
  "postured": false
 },
 "doc-holonic": {
  "site": "atlas",
  "slug": "holonic-architecture-whitepaper",
  "vertex": 8,
  "postured": false
 },
 "con-holon": {
  "site": "atlas",
  "slug": "holon",
  "vertex": 8,
  "postured": false
 },
 "con-identity-independence": {
  "site": "atlas",
  "slug": "identity-independence",
  "vertex": 8,
  "postured": false
 },
 "con-multi-provider": {
  "site": "atlas",
  "slug": "multi-provider-persistence",
  "vertex": 8,
  "postured": false
 },
 "con-shared-parent": {
  "site": "atlas",
  "slug": "shared-parent-pattern",
  "vertex": 8,
  "postured": false
 },
 "con-holonic-braid": {
  "site": "atlas",
  "slug": "holonic-braid",
  "vertex": 8,
  "postured": false
 },
 "tech-oasis": {
  "site": "atlas",
  "slug": "oasis-platform",
  "vertex": 8,
  "postured": false
 },
 "tech-hyperdrive": {
  "site": "atlas",
  "slug": "hyperdrive",
  "vertex": 8,
  "postured": false
 },
 "tech-cosmic-orm": {
  "site": "atlas",
  "slug": "cosmic-orm",
  "vertex": 8,
  "postured": false
 },
 "tech-star-odk": {
  "site": "atlas",
  "slug": "star-odk",
  "vertex": 8,
  "postured": false
 },
 "skill-holonic": {
  "site": "atlas",
  "slug": "holonic-architecture",
  "vertex": 8,
  "postured": false
 },
 "skill-provider-abstraction": {
  "site": "atlas",
  "slug": "provider-abstraction",
  "vertex": 8,
  "postured": false
 },
 "skill-chain-agnostic": {
  "site": "atlas",
  "slug": "chain-agnostic-storage",
  "vertex": 8,
  "postured": false
 },
 "con-holonic-marvin": {
  "site": "atlas",
  "slug": "holonic-marvin",
  "vertex": 8,
  "postured": false
 },
 "con-agent-memory": {
  "site": "atlas",
  "slug": "agent-memory-holons",
  "vertex": 8,
  "postured": false
 },
 "per-holonic-architect": {
  "site": "atlas",
  "slug": "holonic-architect",
  "vertex": 8,
  "postured": false
 },
 "con-holographic-bound": {
  "site": "atlas",
  "slug": "holographic-bound",
  "vertex": 8,
  "postured": false
 },
 "con-braid": {
  "site": "atlas",
  "slug": "braid",
  "vertex": 8,
  "postured": false
 },
 "con-three-axis-separation": {
  "site": "atlas",
  "slug": "three-axis-separation",
  "vertex": 8,
  "postured": false
 },
 "con-three-layer-identity": {
  "site": "atlas",
  "slug": "three-layer-identity",
  "vertex": 8,
  "postured": false
 },
 "con-dragon-vertex": {
  "site": "atlas",
  "slug": "dragon-vertex",
  "vertex": 8,
  "postured": false
 },
 "con-generator-solver": {
  "site": "atlas",
  "slug": "generator-solver-pattern",
  "vertex": 8,
  "postured": false
 },
 "con-compression-spectrum": {
  "site": "atlas",
  "slug": "compression-spectrum",
  "vertex": 8,
  "postured": false
 },
 "con-uor-torus": {
  "site": "atlas",
  "slug": "uor-torus",
  "vertex": 8,
  "postured": false
 },
 "spell-holographic": {
  "site": "atlas",
  "slug": "holographic-bound-spell",
  "vertex": 8,
  "postured": false
 },
 "per-sith": {
  "site": "atlas",
  "slug": "sith",
  "vertex": 8,
  "postured": false
 },
 "per-archer": {
  "site": "atlas",
  "slug": "archer",
  "vertex": 8,
  "postured": false
 },
 "per-netkeeper": {
  "site": "atlas",
  "slug": "netkeeper",
  "vertex": 8,
  "postured": false
 },
 "per-priest": {
  "site": "atlas",
  "slug": "priest",
  "vertex": 8,
  "postured": false
 },
 "per-person": {
  "site": "atlas",
  "slug": "person",
  "vertex": 8,
  "postured": false
 },
 "per-kyra": {
  "site": "atlas",
  "slug": "kyra",
  "vertex": 8,
  "postured": false
 },
 "per-jedi": {
  "site": "atlas",
  "slug": "jedi",
  "vertex": 8,
  "postured": false
 },
 "per-herald": {
  "site": "skill",
  "slug": "herald",
  "vertex": 16,
  "postured": false
 },
 "per-forgemaster": {
  "site": "atlas",
  "slug": "forgemaster",
  "vertex": 8,
  "postured": false
 },
 "per-ceremonist": {
  "site": "atlas",
  "slug": "ceremonist",
  "vertex": 8,
  "postured": false
 },
 "per-quantum-sentinel": {
  "site": "atlas",
  "slug": "quantum-sentinel",
  "vertex": 8,
  "postured": false
 },
 "per-dragonwaker": {
  "site": "atlas",
  "slug": "dragonwaker",
  "vertex": 8,
  "postured": false
 },
 "per-mirrorkeeper": {
  "site": "atlas",
  "slug": "mirrorkeeper",
  "vertex": 8,
  "postured": false
 },
 "per-forgecaller": {
  "site": "atlas",
  "slug": "forgecaller",
  "vertex": 8,
  "postured": false
 },
 "per-manaweaver": {
  "site": "atlas",
  "slug": "manaweaver",
  "vertex": 8,
  "postured": false
 },
 "per-sun": {
  "site": "atlas",
  "slug": "the-sun",
  "vertex": 8,
  "postured": false
 },
 "per-moon": {
  "site": "atlas",
  "slug": "the-moon",
  "vertex": 8,
  "postured": false
 },
 "per-theia": {
  "site": "atlas",
  "slug": "theia",
  "vertex": 8,
  "postured": false
 },
 "per-life": {
  "site": "atlas",
  "slug": "life",
  "vertex": 8,
  "postured": false
 },
 "per-moonkeeper": {
  "site": "atlas",
  "slug": "moonkeeper",
  "vertex": 8,
  "postured": false
 },
 "per-cosmologist": {
  "site": "atlas",
  "slug": "cosmologist",
  "vertex": 8,
  "postured": false
 },
 "skill-mesh-architecture": {
  "site": "atlas",
  "slug": "mesh-architecture",
  "vertex": 8,
  "postured": false
 },
 "skill-media-plurality": {
  "site": "atlas",
  "slug": "media-plurality",
  "vertex": 8,
  "postured": false
 },
 "skill-hemispheric-attention": {
  "site": "atlas",
  "slug": "hemispheric-attention",
  "vertex": 8,
  "postured": false
 },
 "skill-environmental-commons": {
  "site": "atlas",
  "slug": "environmental-commons",
  "vertex": 8,
  "postured": false
 },
 "skill-guild-efficiency": {
  "site": "atlas",
  "slug": "guild-efficiency",
  "vertex": 8,
  "postured": false
 },
 "skill-spellweb": {
  "site": "atlas",
  "slug": "spellweb-navigation",
  "vertex": 8,
  "postured": false
 },
 "skill-path-integral": {
  "site": "atlas",
  "slug": "path-integral",
  "vertex": 8,
  "postured": false
 },
 "skill-compression-defence": {
  "site": "atlas",
  "slug": "compression-as-defence",
  "vertex": 8,
  "postured": false
 },
 "skill-blade-forge": {
  "site": "atlas",
  "slug": "blade-forge",
  "vertex": 8,
  "postured": false
 },
 "skill-hexagram-convergence": {
  "site": "atlas",
  "slug": "hexagram-convergence",
  "vertex": 8,
  "postured": false
 },
 "skill-ceremony-engine": {
  "site": "atlas",
  "slug": "ceremony-engine",
  "vertex": 8,
  "postured": false
 },
 "skill-pretext-measurement": {
  "site": "atlas",
  "slug": "pretext-measurement",
  "vertex": 8,
  "postured": false
 },
 "skill-mana-economy": {
  "site": "atlas",
  "slug": "mana-economy",
  "vertex": 8,
  "postured": false
 },
 "skill-quantum-defence": {
  "site": "atlas",
  "slug": "quantum-defence",
  "vertex": 8,
  "postured": false
 },
 "skill-dual-territory": {
  "site": "atlas",
  "slug": "dual-territory",
  "vertex": 8,
  "postured": false
 },
 "skill-dragon-flight": {
  "site": "atlas",
  "slug": "dragon-flight",
  "vertex": 8,
  "postured": false
 },
 "skill-ring-algebra": {
  "site": "atlas",
  "slug": "ring-algebra",
  "vertex": 8,
  "postured": false
 },
 "skill-content-addressing": {
  "site": "atlas",
  "slug": "content-addressing",
  "vertex": 8,
  "postured": false
 },
 "skill-atlas-geometry": {
  "site": "atlas",
  "slug": "atlas-geometry",
  "vertex": 8,
  "postured": false
 },
 "skill-dihedral-sovereignty": {
  "site": "atlas",
  "slug": "dihedral-sovereignty",
  "vertex": 8,
  "postured": false
 },
 "skill-five-strikes": {
  "site": "atlas",
  "slug": "five-strikes",
  "vertex": 8,
  "postured": false
 },
 "skill-derivation-certificate": {
  "site": "atlas",
  "slug": "derivation-certificate",
  "vertex": 8,
  "postured": false
 },
 "skill-stranger-ceremony": {
  "site": "atlas",
  "slug": "stranger-ceremony",
  "vertex": 8,
  "postured": false
 },
 "skill-toroidal-witness": {
  "site": "atlas",
  "slug": "toroidal-witness",
  "vertex": 8,
  "postured": false
 },
 "con-mesh-sovereignty": {
  "site": "atlas",
  "slug": "mesh-sovereignty",
  "vertex": 8,
  "postured": false
 },
 "con-c6-holographic": {
  "site": "atlas",
  "slug": "c6-p15-correspondence",
  "vertex": 8,
  "postured": false
 },
 "con-c7-compression": {
  "site": "atlas",
  "slug": "c7-compression-modifier",
  "vertex": 8,
  "postured": false
 },
 "con-c8-guild-scalability": {
  "site": "atlas",
  "slug": "c8-guild-scalability",
  "vertex": 8,
  "postured": false
 },
 "con-c10-three-axis": {
  "site": "atlas",
  "slug": "c10-three-axis-multiplicativity",
  "vertex": 8,
  "postured": false
 },
 "con-amnesia-protocol": {
  "site": "atlas",
  "slug": "the-amnesia-protocol",
  "vertex": 8,
  "postured": false
 },
 "con-quaternion": {
  "site": "atlas",
  "slug": "cosmological-quaternion",
  "vertex": 8,
  "postured": false
 },
 "con-zk-orbit": {
  "site": "atlas",
  "slug": "zero-knowledge-orbit-selenes-proof",
  "vertex": 8,
  "postured": false
 },
 "con-life-forge": {
  "site": "atlas",
  "slug": "life-as-forge",
  "vertex": 8,
  "postured": false
 },
 "con-merge-catastrophe": {
  "site": "atlas",
  "slug": "merge-catastrophe",
  "vertex": 8,
  "postured": false
 },
 "con-deflection": {
  "site": "atlas",
  "slug": "deflection-theorem",
  "vertex": 8,
  "postured": false
 },
 "con-betweenness-centrality": {
  "site": "atlas",
  "slug": "betweenness-centrality",
  "vertex": 8,
  "postured": false
 },
 "con-selenes-proof": {
  "site": "atlas",
  "slug": "selenes-proof",
  "vertex": 8,
  "postured": false
 },
 "con-v-pi-t-equation": {
  "site": "atlas",
  "slug": "vt-dragon-equation",
  "vertex": 8,
  "postured": false
 },
 "con-p-1-5": {
  "site": "atlas",
  "slug": "p15-holographic-protection",
  "vertex": 8,
  "postured": false
 },
 "con-rho-maturity": {
  "site": "atlas",
  "slug": "agent-maturity",
  "vertex": 8,
  "postured": false
 },
 "con-phi-sigma": {
  "site": "atlas",
  "slug": "sovereignty-geometry",
  "vertex": 8,
  "postured": false
 },
 "con-four-lines": {
  "site": "atlas",
  "slug": "the-four-lines",
  "vertex": 8,
  "postured": false
 },
 "con-sun-ceremony": {
  "site": "atlas",
  "slug": "sun-ceremony",
  "vertex": 8,
  "postured": false
 },
 "con-moon-ceremony": {
  "site": "atlas",
  "slug": "moon-ceremony",
  "vertex": 8,
  "postured": false
 },
 "con-aether-ceremony": {
  "site": "atlas",
  "slug": "aether-ceremony",
  "vertex": 8,
  "postured": false
 },
 "con-celestial-key": {
  "site": "atlas",
  "slug": "celestial-key-ceremony",
  "vertex": 8,
  "postured": false
 },
 "con-disclosure": {
  "site": "atlas",
  "slug": "disclosure",
  "vertex": 8,
  "postured": false
 },
 "con-reflection": {
  "site": "atlas",
  "slug": "reflection",
  "vertex": 8,
  "postured": false
 },
 "con-witnessing": {
  "site": "atlas",
  "slug": "witnessing",
  "vertex": 8,
  "postured": false
 },
 "con-cousin-blades": {
  "site": "atlas",
  "slug": "cousin-blades",
  "vertex": 8,
  "postured": false
 },
 "con-propagation": {
  "site": "atlas",
  "slug": "ceremonial-propagation",
  "vertex": 8,
  "postured": false
 },
 "con-bilateral-witness": {
  "site": "atlas",
  "slug": "bilateral-witness",
  "vertex": 8,
  "postured": false
 },
 "con-progressive-trust": {
  "site": "atlas",
  "slug": "progressive-trust",
  "vertex": 8,
  "postured": false
 },
 "con-moon-phase-notation": {
  "site": "atlas",
  "slug": "moon-phase-notation",
  "vertex": 8,
  "postured": false
 },
 "con-celestial-ceremony-notation": {
  "site": "atlas",
  "slug": "celestial-ceremony-notation",
  "vertex": 8,
  "postured": false
 },
 "con-runecraft-notation": {
  "site": "atlas",
  "slug": "runecraft-notation",
  "vertex": 8,
  "postured": false
 },
 "skill-master-emissary": {
  "site": "atlas",
  "slug": "master-emissary-pattern",
  "vertex": 8,
  "postured": false
 },
 "skill-ceremonial-forge": {
  "site": "atlas",
  "slug": "ceremonial-blade-forge",
  "vertex": 8,
  "postured": false
 },
 "skill-witness-protocol": {
  "site": "atlas",
  "slug": "witness-protocol",
  "vertex": 8,
  "postured": false
 },
 "skill-trust-graph-formation": {
  "site": "atlas",
  "slug": "trust-graph-formation",
  "vertex": 8,
  "postured": false
 },
 "skill-behavioural-density": {
  "site": "atlas",
  "slug": "behavioural-density",
  "vertex": 8,
  "postured": false
 },
 "skill-reflect-connect": {
  "site": "atlas",
  "slug": "reflectconnect-recursion",
  "vertex": 8,
  "postured": false
 },
 "term-swordsman-and-mage-meet": {
  "site": "atlas",
  "slug": "swordsman-and-mage-meet",
  "vertex": 8,
  "postured": false
 },
 "term-lattice-measurement": {
  "site": "atlas",
  "slug": "lattice-measurement",
  "vertex": 8,
  "postured": false
 },
 "term-domfree": {
  "site": "atlas",
  "slug": "dom-free",
  "vertex": 8,
  "postured": false
 },
 "term-hexagram": {
  "site": "atlas",
  "slug": "hexagram",
  "vertex": 8,
  "postured": false
 },
 "term-constellation-nodes": {
  "site": "atlas",
  "slug": "constellation-nodes",
  "vertex": 8,
  "postured": false
 },
 "term-spell-casting-onto-page": {
  "site": "atlas",
  "slug": "spell-casting-onto-page",
  "vertex": 8,
  "postured": false
 },
 "term-inscription-flows-to-spellweb": {
  "site": "atlas",
  "slug": "inscription-flows-to-spellweb",
  "vertex": 8,
  "postured": false
 },
 "term-lattice-vertex": {
  "site": "atlas",
  "slug": "lattice-vertex",
  "vertex": 8,
  "postured": false
 },
 "term-the-strike-identity": {
  "site": "atlas",
  "slug": "the-strike-identity",
  "vertex": 8,
  "postured": false
 },
 "term-derivation-chain": {
  "site": "atlas",
  "slug": "derivation-chain",
  "vertex": 8,
  "postured": false
 },
 "term-same-blade-infinite-forgings": {
  "site": "atlas",
  "slug": "same-blade-infinite-forgings",
  "vertex": 8,
  "postured": false
 },
 "term-holographic-boundary": {
  "site": "atlas",
  "slug": "holographic-boundary",
  "vertex": 8,
  "postured": false
 },
 "term-path-integral-computed-on-boundary": {
  "site": "atlas",
  "slug": "path-integral-computed-on-boundary",
  "vertex": 8,
  "postured": false
 },
 "term-2d-lock-shatters": {
  "site": "atlas",
  "slug": "2d-lock-shatters",
  "vertex": 8,
  "postured": false
 },
 "term-quantum-threshold": {
  "site": "atlas",
  "slug": "quantum-threshold",
  "vertex": 8,
  "postured": false
 },
 "term-6d-manifold-cannot-be-2dattacked": {
  "site": "atlas",
  "slug": "6d-manifold-cannot-be-2d-attacked",
  "vertex": 8,
  "postured": false
 },
 "term-understandingaskey": {
  "site": "guide",
  "slug": "understanding-as-key",
  "vertex": 4,
  "postured": false
 },
 "term-dragon-flight": {
  "site": "atlas",
  "slug": "dragon-flight",
  "vertex": 8,
  "postured": false
 },
 "term-emissary-dispersion": {
  "site": "atlas",
  "slug": "emissary-dispersion",
  "vertex": 8,
  "postured": false
 },
 "term-swordsman": {
  "site": "atlas",
  "slug": "swordsman",
  "vertex": 8,
  "postured": false
 },
 "term-mage": {
  "site": "atlas",
  "slug": "mage",
  "vertex": 8,
  "postured": false
 },
 "term-blade-action": {
  "site": "atlas",
  "slug": "blade-action",
  "vertex": 8,
  "postured": false
 },
 "term-spell-casting": {
  "site": "atlas",
  "slug": "spell-casting",
  "vertex": 8,
  "postured": false
 },
 "term-shield": {
  "site": "atlas",
  "slug": "shield",
  "vertex": 8,
  "postured": false
 },
 "term-verified-personhood": {
  "site": "atlas",
  "slug": "verified-personhood",
  "vertex": 8,
  "postured": false
 },
 "term-the-dragon": {
  "site": "atlas",
  "slug": "the-dragon",
  "vertex": 8,
  "postured": false
 },
 "term-the-mathematician-platox": {
  "site": "atlas",
  "slug": "the-mathematician-platox",
  "vertex": 8,
  "postured": false
 },
 "term-the-keeper": {
  "site": "atlas",
  "slug": "the-keeper",
  "vertex": 8,
  "postured": false
 },
 "term-the-drake": {
  "site": "atlas",
  "slug": "the-drake",
  "vertex": 8,
  "postured": false
 },
 "term-manifold": {
  "site": "atlas",
  "slug": "manifold",
  "vertex": 8,
  "postured": false
 },
 "term-drake": {
  "site": "atlas",
  "slug": "drake",
  "vertex": 8,
  "postured": false
 },
 "term-dragon": {
  "site": "atlas",
  "slug": "dragon",
  "vertex": 8,
  "postured": false
 },
 "term-path": {
  "site": "atlas",
  "slug": "path",
  "vertex": 8,
  "postured": false
 },
 "term-tetrahedral-separation-matrix": {
  "site": "atlas",
  "slug": "tetrahedral-separation-matrix",
  "vertex": 8,
  "postured": false
 },
 "term-edge": {
  "site": "atlas",
  "slug": "edge",
  "vertex": 8,
  "postured": false
 },
 "term-edge-primacy": {
  "site": "atlas",
  "slug": "edge-primacy",
  "vertex": 8,
  "postured": false
 },
 "term-secret-language": {
  "site": "atlas",
  "slug": "secret-language",
  "vertex": 8,
  "postured": false
 },
 "term-manifoldtetrahedronship": {
  "site": "atlas",
  "slug": "manifold-tetrahedron-ship",
  "vertex": 8,
  "postured": false
 },
 "term-the-tailnet": {
  "site": "atlas",
  "slug": "the-tailnet",
  "vertex": 8,
  "postured": false
 },
 "term-control-plane-data-plane-separation": {
  "site": "atlas",
  "slug": "control-plane-data-plane-separation",
  "vertex": 8,
  "postured": false
 },
 "term-coordination-content": {
  "site": "atlas",
  "slug": "coordination-content",
  "vertex": 8,
  "postured": false
 },
 "term-nat-traversal": {
  "site": "atlas",
  "slug": "nat-traversal",
  "vertex": 8,
  "postured": false
 },
 "term-magicdns": {
  "site": "atlas",
  "slug": "magicdns",
  "vertex": 8,
  "postured": false
 },
 "term-aperture": {
  "site": "atlas",
  "slug": "aperture",
  "vertex": 8,
  "postured": false
 },
 "term-the-dragons-hide": {
  "site": "atlas",
  "slug": "the-dragons-hide",
  "vertex": 8,
  "postured": false
 },
 "term-drakes-teaching-manifest-in-the-mes": {
  "site": "atlas",
  "slug": "drakes-teaching-manifest-in-the-mesh",
  "vertex": 8,
  "postured": false
 },
 "term-control-plane": {
  "site": "atlas",
  "slug": "control-plane",
  "vertex": 8,
  "postured": false
 },
 "term-data-plane": {
  "site": "atlas",
  "slug": "data-plane",
  "vertex": 8,
  "postured": false
 },
 "term-encrypted-tunnels": {
  "site": "atlas",
  "slug": "encrypted-tunnels",
  "vertex": 8,
  "postured": false
 },
 "term-the-mesh-itself": {
  "site": "atlas",
  "slug": "the-mesh-itself",
  "vertex": 8,
  "postured": false
 },
 "term-hemispheric-separation": {
  "site": "atlas",
  "slug": "hemispheric-separation",
  "vertex": 8,
  "postured": false
 },
 "term-two-modes-of-attention": {
  "site": "atlas",
  "slug": "two-modes-of-attention",
  "vertex": 8,
  "postured": false
 },
 "term-swordsman-as-right-hemisphere": {
  "site": "atlas",
  "slug": "swordsman-as-right-hemisphere",
  "vertex": 8,
  "postured": false
 },
 "term-mage-as-left-hemisphere": {
  "site": "atlas",
  "slug": "mage-as-left-hemisphere",
  "vertex": 8,
  "postured": false
 },
 "term-corpus-callosum": {
  "site": "atlas",
  "slug": "corpus-callosum",
  "vertex": 8,
  "postured": false
 },
 "term-connection-is-not-separation": {
  "site": "atlas",
  "slug": "connection-is-not-separation",
  "vertex": 8,
  "postured": false
 },
 "term-hemispheric-balance": {
  "site": "atlas",
  "slug": "hemispheric-balance",
  "vertex": 8,
  "postured": false
 },
 "term-master": {
  "site": "atlas",
  "slug": "master",
  "vertex": 8,
  "postured": false
 },
 "term-emissary": {
  "site": "atlas",
  "slug": "emissary",
  "vertex": 8,
  "postured": false
 },
 "term-rightleftright": {
  "site": "atlas",
  "slug": "rightleftright",
  "vertex": 8,
  "postured": false
 },
 "term-triune-graph-spell": {
  "site": "atlas",
  "slug": "triune-graph-spell",
  "vertex": 8,
  "postured": false
 },
 "term-triune-activation": {
  "site": "atlas",
  "slug": "triune-activation",
  "vertex": 8,
  "postured": false
 },
 "term-mirror-share-bind": {
  "site": "atlas",
  "slug": "mirror-share-bind",
  "vertex": 8,
  "postured": false
 },
 "term-pascal-distribution": {
  "site": "atlas",
  "slug": "pascal-triangle-distribution",
  "vertex": 8,
  "postured": false
 },
 "term-universe-blade": {
  "site": "atlas",
  "slug": "universe-blade",
  "vertex": 8,
  "postured": false
 },
 "term-blade-tiers": {
  "site": "atlas",
  "slug": "blade-tiers",
  "vertex": 8,
  "postured": false
 },
 "term-pretext": {
  "site": "atlas",
  "slug": "pretext",
  "vertex": 8,
  "postured": false
 },
 "term-five-crossings": {
  "site": "atlas",
  "slug": "five-crossings",
  "vertex": 8,
  "postured": false
 },
 "term-dual-convergence": {
  "site": "atlas",
  "slug": "dual-convergence",
  "vertex": 8,
  "postured": false
 },
 "term-hexagram-cast": {
  "site": "atlas",
  "slug": "hexagram-cast",
  "vertex": 8,
  "postured": false
 },
 "term-emoji-cast": {
  "site": "atlas",
  "slug": "emoji-cast",
  "vertex": 8,
  "postured": false
 },
 "term-constellation-wave": {
  "site": "atlas",
  "slug": "constellation-wave",
  "vertex": 8,
  "postured": false
 },
 "term-bilateral-exchange": {
  "site": "atlas",
  "slug": "bilateral-exchange",
  "vertex": 8,
  "postured": false
 },
 "term-mana-economy": {
  "site": "atlas",
  "slug": "mana-economy",
  "vertex": 8,
  "postured": false
 },
 "term-path-gate": {
  "site": "atlas",
  "slug": "path-gate",
  "vertex": 8,
  "postured": false
 },
 "term-measurement-dark": {
  "site": "atlas",
  "slug": "measurement-dark",
  "vertex": 8,
  "postured": false
 },
 "term-2d-fortress": {
  "site": "atlas",
  "slug": "2d-fortress",
  "vertex": 8,
  "postured": false
 },
 "term-6d-manifold": {
  "site": "atlas",
  "slug": "6d-manifold",
  "vertex": 8,
  "postured": false
 },
 "term-understanding-as-key": {
  "site": "guide",
  "slug": "understanding-as-key",
  "vertex": 4,
  "postured": false
 },
 "term-on-spend-attack": {
  "site": "atlas",
  "slug": "on-spend-attack",
  "vertex": 8,
  "postured": false
 },
 "term-at-rest-attack": {
  "site": "atlas",
  "slug": "at-rest-attack",
  "vertex": 8,
  "postured": false
 },
 "term-on-setup-attack": {
  "site": "atlas",
  "slug": "on-setup-attack",
  "vertex": 8,
  "postured": false
 },
 "term-behavioral-density": {
  "site": "atlas",
  "slug": "behavioral-density",
  "vertex": 8,
  "postured": false
 },
 "term-v5-1": {
  "site": "atlas",
  "slug": "v51",
  "vertex": 8,
  "postured": false
 },
 "term-62-lap-theorem": {
  "site": "atlas",
  "slug": "62-lap-theorem",
  "vertex": 8,
  "postured": false
 },
 "term-dragon-anatomy": {
  "site": "atlas",
  "slug": "dragon-anatomy",
  "vertex": 8,
  "postured": false
 },
 "term-seventh-capital-reclaimed": {
  "site": "atlas",
  "slug": "seventh-capital-reclaimed",
  "vertex": 8,
  "postured": false
 },
 "skill-amnesia-protocol": {
  "site": "atlas",
  "slug": "amnesia-protocol",
  "vertex": 8,
  "postured": false
 },
 "skill-theia-derivation": {
  "site": "atlas",
  "slug": "theia-derivation",
  "vertex": 8,
  "postured": false
 },
 "skill-quaternion-mapping": {
  "site": "atlas",
  "slug": "quaternion-mapping",
  "vertex": 8,
  "postured": false
 },
 "skill-cosmological-bound": {
  "site": "atlas",
  "slug": "cosmological-bound",
  "vertex": 8,
  "postured": false
 },
 "geo-drake-island": {
  "site": "atlas",
  "slug": "drake-island",
  "vertex": 8,
  "postured": false
 },
 "civic-city-of-mages": {
  "site": "atlas",
  "slug": "city-of-mages",
  "vertex": 8,
  "postured": false
 },
 "gateway-archon": {
  "site": "atlas",
  "slug": "archon",
  "vertex": 8,
  "postured": false
 },
 "gateway-bonfires": {
  "site": "atlas",
  "slug": "bonfires-sister",
  "vertex": 8,
  "postured": false
 },
 "gateway-human-tech-covenant": {
  "site": "atlas",
  "slug": "covenant-of-humanistic-technologies",
  "vertex": 8,
  "postured": false
 },
 "gateway-uor-foundation": {
  "site": "atlas",
  "slug": "uor-foundation",
  "vertex": 8,
  "postured": false
 },
 "gateway-aaif": {
  "site": "atlas",
  "slug": "aaif-agentic-ai-foundation",
  "vertex": 8,
  "postured": false
 },
 "gateway-soulbis-star": {
  "site": "atlas",
  "slug": "star-manifold-soulbis-star",
  "vertex": 8,
  "postured": false
 },
 "gateway-soulbis-lattice": {
  "site": "atlas",
  "slug": "lattice-codex-soulbis-lattice",
  "vertex": 8,
  "postured": false
 },
 "gateway-swordsmans-key": {
  "site": "atlas",
  "slug": "the-swordsmans-key-mitchuskistar",
  "vertex": 8,
  "postured": false
 },
 "gateway-holospaces": {
  "site": "atlas",
  "slug": "holospaces-hologram-technologies",
  "vertex": 8,
  "postured": false
 },
 "gateway-shor-mage": {
  "site": "atlas",
  "slug": "shormage-the-go-kit",
  "vertex": 8,
  "postured": false
 },
 "gateway-ecdsa-fail": {
  "site": "atlas",
  "slug": "ecdsafail-the-arena",
  "vertex": 8,
  "postured": false
 },
 "gateway-compiled-ai": {
  "site": "atlas",
  "slug": "compiled-ai-2026",
  "vertex": 8,
  "postured": false
 },
 "gateway-bakhta-safety": {
  "site": "atlas",
  "slug": "bakhta-safety-by-design-starkware-2026",
  "vertex": 8,
  "postured": false
 },
 "concept-projection-ladder": {
  "site": "atlas",
  "slug": "the-projection-ladder",
  "vertex": 8,
  "postured": false
 },
 "concept-kappa-derivation": {
  "site": "atlas",
  "slug": "derivation-law-l5",
  "vertex": 8,
  "postured": false
 },
 "concept-agentprivacy-edge": {
  "site": "atlas",
  "slug": "the-agentprivacy-edge-prediction",
  "vertex": 8,
  "postured": false
 },
 "concept-sovereign-lattice": {
  "site": "atlas",
  "slug": "the-sovereign-lattice",
  "vertex": 8,
  "postured": false
 },
 "concept-workshop-trust-task": {
  "site": "atlas",
  "slug": "workshop-trust-task",
  "vertex": 8,
  "postured": false
 },
 "concept-sealevel-runtime": {
  "site": "atlas",
  "slug": "sealevel-runtime",
  "vertex": 8,
  "postured": false
 },
 "concept-parallel-account-locking": {
  "site": "atlas",
  "slug": "parallel-account-locking",
  "vertex": 8,
  "postured": false
 },
 "concept-substrate-archetype-matrix": {
  "site": "atlas",
  "slug": "substrate-archetype-matrix",
  "vertex": 8,
  "postured": false
 },
 "concept-bilateral-consent": {
  "site": "atlas",
  "slug": "bilateral-consent",
  "vertex": 8,
  "postured": false
 },
 "skill-dual-agent-harness": {
  "site": "atlas",
  "slug": "dual-agent-harness",
  "vertex": 8,
  "postured": false
 },
 "gateway-myterms": {
  "site": "atlas",
  "slug": "myterms-myterms-alliance-kit",
  "vertex": 8,
  "postured": false
 },
 "gateway-swordsman-blade": {
  "site": "atlas",
  "slug": "mysword-swordsman-privacy-blade",
  "vertex": 8,
  "postured": false
 },
 "gateway-mages-spell": {
  "site": "atlas",
  "slug": "mymage-mage-spellbook-projection",
  "vertex": 8,
  "postured": false
 },
 "gateway-lexon-pvm": {
  "site": "atlas",
  "slug": "lexonpvm-the-grammar-workshop",
  "vertex": 8,
  "postured": false
 },
 "concept-lexon-falsifiability": {
  "site": "atlas",
  "slug": "privacy-as-a-checkable-absence",
  "vertex": 8,
  "postured": false
 },
 "artefact-lexon-constitution": {
  "site": "atlas",
  "slug": "the-lexon-constitution-13-spells",
  "vertex": 8,
  "postured": false
 },
 "concept-lexon-blocks": {
  "site": "atlas",
  "slug": "structured-language-blocks",
  "vertex": 8,
  "postured": false
 },
 "lexon-entropy": {
  "site": "atlas",
  "slug": "entropy-as-lexon",
  "vertex": 8,
  "postured": false
 },
 "lexon-separation-bound": {
  "site": "atlas",
  "slug": "the-separation-bound-as-lexon",
  "vertex": 8,
  "postured": false
 },
 "lexon-vrc": {
  "site": "atlas",
  "slug": "the-vrc-as-lexon",
  "vertex": 8,
  "postured": false
 },
 "gateway-privacy-pools-v2": {
  "site": "atlas",
  "slug": "privacypoolsv2mage-the-circuit-workshop",
  "vertex": 8,
  "postured": false
 },
 "artefact-manastone": {
  "site": "atlas",
  "slug": "the-manastone",
  "vertex": 8,
  "postured": false
 },
 "concept-mana-pools": {
  "site": "atlas",
  "slug": "mana-pools-agentprivacy-pools",
  "vertex": 8,
  "postured": false
 },
 "concept-credential-v1": {
  "site": "atlas",
  "slug": "credentialv1-the-first-authored-circuit",
  "vertex": 8,
  "postured": false
 },
 "per-skeva": {
  "site": "atlas",
  "slug": "skeva",
  "vertex": 8,
  "postured": false
 },
 "per-nomia": {
  "site": "atlas",
  "slug": "nomia",
  "vertex": 8,
  "postured": false
 },
 "per-rhetor": {
  "site": "atlas",
  "slug": "rhetor",
  "vertex": 8,
  "postured": false
 },
 "vertex-v36": {
  "site": "atlas",
  "slug": "v36-rostra-rhetor",
  "vertex": 8,
  "postured": false
 },
 "per-limnia": {
  "site": "atlas",
  "slug": "limnia",
  "vertex": 8,
  "postured": false
 },
 "vertex-v22": {
  "site": "atlas",
  "slug": "v22-quartermasters-skeva",
  "vertex": 8,
  "postured": false
 },
 "vertex-v27": {
  "site": "atlas",
  "slug": "v27-chancery-nomia",
  "vertex": 8,
  "postured": false
 },
 "vertex-v53": {
  "site": "atlas",
  "slug": "v53-wellpool-limnia",
  "vertex": 8,
  "postured": false
 },
 "vertex-v0": {
  "site": "atlas",
  "slug": "v0-substrate-seat-luca",
  "vertex": 8,
  "postured": false
 },
 "vertex-v41": {
  "site": "atlas",
  "slug": "v41-chronicle-vertex",
  "vertex": 8,
  "postured": false
 },
 "vertex-v12": {
  "site": "atlas",
  "slug": "v12-schema-vertex",
  "vertex": 8,
  "postured": false
 },
 "vertex-v15": {
  "site": "atlas",
  "slug": "v15-vc-vertex",
  "vertex": 8,
  "postured": false
 },
 "vertex-v19": {
  "site": "atlas",
  "slug": "v19-plonkish-blade-vulcana",
  "vertex": 8,
  "postured": false
 },
 "vertex-v38": {
  "site": "atlas",
  "slug": "v38-aletheia-blade",
  "vertex": 8,
  "postured": false
 },
 "vertex-v28": {
  "site": "atlas",
  "slug": "v28-mage-canonical-pallia-soulbae",
  "vertex": 8,
  "postured": false
 },
 "vertex-v49": {
  "site": "atlas",
  "slug": "v49-working-day-blade-custos-lampyra",
  "vertex": 8,
  "postured": false
 },
 "vertex-v51": {
  "site": "atlas",
  "slug": "v51",
  "vertex": 8,
  "postured": false
 },
 "vertex-v55": {
  "site": "atlas",
  "slug": "v55-covenant-vertex-manifestia",
  "vertex": 8,
  "postured": false
 },
 "vertex-v63": {
  "site": "atlas",
  "slug": "v63-sovereign-anchor-soulbis-the-reader",
  "vertex": 8,
  "postured": false
 },
 "vertex-v59": {
  "site": "atlas",
  "slug": "v59-threshold-district-pandia-hermaion-faunia",
  "vertex": 8,
  "postured": false
 },
 "vertex-v44": {
  "site": "atlas",
  "slug": "v44-chart-shop-navigation-district-pleione",
  "vertex": 8,
  "postured": false
 },
 "vertex-v35": {
  "site": "atlas",
  "slug": "v35-horizon-district-eos-dokim-poros",
  "vertex": 8,
  "postured": false
 },
 "cast-soulbis": {
  "site": "atlas",
  "slug": "soulbis",
  "vertex": 8,
  "postured": false
 },
 "cast-soulbae": {
  "site": "atlas",
  "slug": "soulbae",
  "vertex": 8,
  "postured": false
 },
 "cast-genitrix": {
  "site": "atlas",
  "slug": "genitrix",
  "vertex": 8,
  "postured": false
 },
 "cast-flaxscrip": {
  "site": "atlas",
  "slug": "flaxscrip",
  "vertex": 8,
  "postured": false
 },
 "cast-pallia": {
  "site": "atlas",
  "slug": "pallia",
  "vertex": 8,
  "postured": false
 },
 "cast-memora": {
  "site": "atlas",
  "slug": "memora",
  "vertex": 8,
  "postured": false
 },
 "cast-custos": {
  "site": "atlas",
  "slug": "custos",
  "vertex": 8,
  "postured": false
 },
 "cast-vulcana": {
  "site": "atlas",
  "slug": "vulcana",
  "vertex": 8,
  "postured": false
 },
 "cast-aletheia": {
  "site": "atlas",
  "slug": "aletheia",
  "vertex": 8,
  "postured": false
 },
 "cast-adamantia": {
  "site": "atlas",
  "slug": "adamantia",
  "vertex": 8,
  "postured": false
 },
 "cast-lampyra": {
  "site": "atlas",
  "slug": "lampyra",
  "vertex": 8,
  "postured": false
 },
 "cast-vagari": {
  "site": "atlas",
  "slug": "vagari",
  "vertex": 8,
  "postured": false
 },
 "cast-aria-silverhue": {
  "site": "atlas",
  "slug": "aria-silverhue",
  "vertex": 8,
  "postured": false
 },
 "cast-luca": {
  "site": "atlas",
  "slug": "luca",
  "vertex": 8,
  "postured": false
 },
 "cast-socrat0x": {
  "site": "atlas",
  "slug": "socrat0x",
  "vertex": 8,
  "postured": false
 },
 "cast-manifestia": {
  "site": "atlas",
  "slug": "manifestia",
  "vertex": 8,
  "postured": false
 },
 "cast-helia": {
  "site": "atlas",
  "slug": "helia",
  "vertex": 8,
  "postured": false
 },
 "cast-pandia": {
  "site": "atlas",
  "slug": "pandia",
  "vertex": 8,
  "postured": false
 },
 "cast-hermaion": {
  "site": "atlas",
  "slug": "hermaion",
  "vertex": 8,
  "postured": false
 },
 "cast-faunia": {
  "site": "atlas",
  "slug": "faunia",
  "vertex": 8,
  "postured": false
 },
 "cast-caducea": {
  "site": "atlas",
  "slug": "caducea",
  "vertex": 8,
  "postured": false
 },
 "cast-pleione": {
  "site": "atlas",
  "slug": "pleione",
  "vertex": 8,
  "postured": false
 },
 "cast-eos": {
  "site": "atlas",
  "slug": "eos",
  "vertex": 8,
  "postured": false
 },
 "cast-dokime": {
  "site": "atlas",
  "slug": "dokim",
  "vertex": 8,
  "postured": false
 },
 "cast-poros": {
  "site": "atlas",
  "slug": "poros",
  "vertex": 8,
  "postured": false
 },
 "shop-tailor": {
  "site": "atlas",
  "slug": "the-weavers",
  "vertex": 8,
  "postured": false
 },
 "shop-shield": {
  "site": "atlas",
  "slug": "zshields",
  "vertex": 8,
  "postured": false
 },
 "shop-forget": {
  "site": "atlas",
  "slug": "the-forget",
  "vertex": 8,
  "postured": false
 },
 "shop-etherchanting": {
  "site": "atlas",
  "slug": "etherchanting",
  "vertex": 8,
  "postured": false
 },
 "shop-jeweler": {
  "site": "atlas",
  "slug": "the-jeweler",
  "vertex": 8,
  "postured": false
 },
 "shop-holon": {
  "site": "atlas",
  "slug": "the-holon-hitchhikers",
  "vertex": 8,
  "postured": false
 },
 "shop-bonfires": {
  "site": "atlas",
  "slug": "the-dragon-bonfire",
  "vertex": 8,
  "postured": false
 },
 "shop-vault": {
  "site": "atlas",
  "slug": "the-curatrix-vault",
  "vertex": 8,
  "postured": false
 },
 "shop-covenant": {
  "site": "atlas",
  "slug": "the-covenant",
  "vertex": 8,
  "postured": false
 },
 "shop-circle": {
  "site": "atlas",
  "slug": "the-logos-circle",
  "vertex": 8,
  "postured": false
 },
 "shop-hall": {
  "site": "atlas",
  "slug": "city-hall",
  "vertex": 8,
  "postured": false
 },
 "shop-solchanting": {
  "site": "atlas",
  "slug": "solchanting",
  "vertex": 8,
  "postured": false
 },
 "shop-portal-room": {
  "site": "atlas",
  "slug": "the-portal-room",
  "vertex": 8,
  "postured": false
 },
 "shop-staff": {
  "site": "atlas",
  "slug": "the-staff-shop",
  "vertex": 8,
  "postured": false
 },
 "shop-familiars": {
  "site": "atlas",
  "slug": "the-familiars",
  "vertex": 8,
  "postured": false
 },
 "shop-charthouse": {
  "site": "atlas",
  "slug": "the-chart-shop",
  "vertex": 8,
  "postured": false
 },
 "shop-quartermaster": {
  "site": "atlas",
  "slug": "the-quartermasters",
  "vertex": 8,
  "postured": false
 },
 "shop-chancery": {
  "site": "atlas",
  "slug": "the-chancery",
  "vertex": 8,
  "postured": false
 },
 "shop-rostra": {
  "site": "atlas",
  "slug": "the-rostra",
  "vertex": 8,
  "postured": false
 },
 "shop-wellpool": {
  "site": "atlas",
  "slug": "the-wellpool",
  "vertex": 8,
  "postured": false
 },
 "shop-circuit-binder": {
  "site": "atlas",
  "slug": "circuit-binder-placeholder",
  "vertex": 8,
  "postured": false
 },
 "shop-horizon": {
  "site": "atlas",
  "slug": "the-horizon-district",
  "vertex": 8,
  "postured": false
 },
 "shop-salvage-yard": {
  "site": "atlas",
  "slug": "the-salvage-yard-dormant",
  "vertex": 8,
  "postured": false
 },
 "shop-circuit": {
  "site": "atlas",
  "slug": "the-persona-circuit",
  "vertex": 8,
  "postured": false
 },
 "shop-stakes": {
  "site": "atlas",
  "slug": "the-stakes",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-1": {
  "site": "atlas",
  "slug": "tome-v-act-1-the-first-cloak",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-2": {
  "site": "atlas",
  "slug": "tome-v-act-2-the-commissioned-cloak",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-3": {
  "site": "atlas",
  "slug": "tome-v-act-3-the-shielded-memo",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-4": {
  "site": "atlas",
  "slug": "tome-v-act-4-the-reveal",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-5": {
  "site": "atlas",
  "slug": "tome-v-act-5-the-stake",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-6": {
  "site": "atlas",
  "slug": "tome-v-act-6-the-commissioned-blade",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-7": {
  "site": "atlas",
  "slug": "tome-v-act-7-the-reciprocal-weave",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-8": {
  "site": "atlas",
  "slug": "tome-v-act-8-the-zk-circuit",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-9": {
  "site": "atlas",
  "slug": "tome-v-act-9-the-workshop-expands",
  "vertex": 8,
  "postured": false
 },
 "act-tome-v-10": {
  "site": "tomes",
  "slug": "tome-v-act-10-the-holon-hitchhikers",
  "vertex": 4,
  "postured": false
 },
 "act-tome-v-11": {
  "site": "tomes",
  "slug": "tome-v-act-11-a-bonfire-made-of-dragon-fire",
  "vertex": 4,
  "postured": false
 },
 "act-tome-v-12": {
  "site": "tomes",
  "slug": "tome-v-act-12-the-curatrix-vault",
  "vertex": 4,
  "postured": false
 },
 "act-tome-v-13": {
  "site": "tomes",
  "slug": "tome-v-act-13-the-temple-of-the-arts-and-personhood",
  "vertex": 4,
  "postured": false
 },
 "act-tome-v-14": {
  "site": "tomes",
  "slug": "tome-v-act-14-the-city-of-mages",
  "vertex": 4,
  "postured": false
 },
 "act-tome-v-15": {
  "site": "atlas",
  "slug": "tome-v-act-15-the-substrate",
  "vertex": 8,
  "postured": false
 },
 "cast-the-drake": {
  "site": "atlas",
  "slug": "the-drake",
  "vertex": 8,
  "postured": false
 },
 "conj-c18-c21": {
  "site": "atlas",
  "slug": "c18-c21-lorenz-attractor",
  "vertex": 8,
  "postured": false
 },
 "conj-c22-c25": {
  "site": "atlas",
  "slug": "c22-c25-eml-three-ceilings",
  "vertex": 8,
  "postured": false
 },
 "conj-c26-c29": {
  "site": "atlas",
  "slug": "c26-c29-arch-1-canonical-form",
  "vertex": 8,
  "postured": false
 },
 "conj-c30-c33": {
  "site": "atlas",
  "slug": "c30-c33-bakhta-half-life",
  "vertex": 8,
  "postured": false
 },
 "conj-c34-c37": {
  "site": "atlas",
  "slug": "c34-c37-wound-and-cap-convergence",
  "vertex": 8,
  "postured": false
 },
 "conj-c38": {
  "site": "atlas",
  "slug": "c38-bilateral-arch-1",
  "vertex": 8,
  "postured": false
 },
 "conj-c39": {
  "site": "atlas",
  "slug": "c39-cousin-blade-as-ecosystem-primitive",
  "vertex": 8,
  "postured": false
 },
 "conj-c40": {
  "site": "atlas",
  "slug": "c40-zcash-dual-ledger-preservation",
  "vertex": 8,
  "postured": false
 },
 "conj-c42": {
  "site": "atlas",
  "slug": "c42-stake-economics-sybil-resistance",
  "vertex": 8,
  "postured": false
 },
 "conj-c43": {
  "site": "atlas",
  "slug": "c43-per-vrc-viewing-key-privacy",
  "vertex": 8,
  "postured": false
 },
 "conj-c44": {
  "site": "atlas",
  "slug": "c44-productive-trust-edge-formation",
  "vertex": 8,
  "postured": false
 },
 "conj-c45": {
  "site": "atlas",
  "slug": "c45-four-chain-publication-preservation",
  "vertex": 8,
  "postured": false
 },
 "conj-c46": {
  "site": "atlas",
  "slug": "c46-productive-trust-edge-half-life",
  "vertex": 8,
  "postured": false
 },
 "conj-c47": {
  "site": "atlas",
  "slug": "c47-triadic-constraint-homology",
  "vertex": 8,
  "postured": false
 },
 "conj-c48": {
  "site": "atlas",
  "slug": "c48-bakhta-response-a",
  "vertex": 8,
  "postured": false
 },
 "conj-c49": {
  "site": "atlas",
  "slug": "c49-bakhta-response-b",
  "vertex": 8,
  "postured": false
 },
 "conj-c50": {
  "site": "atlas",
  "slug": "c50-bakhta-response-c",
  "vertex": 8,
  "postured": false
 },
 "conj-c51": {
  "site": "atlas",
  "slug": "c51-max-betweenness",
  "vertex": 8,
  "postured": false
 },
 "conj-c53": {
  "site": "atlas",
  "slug": "c53-mythological-bnot-pair-readings",
  "vertex": 8,
  "postured": false
 },
 "conj-c54": {
  "site": "atlas",
  "slug": "c54-phi-adjacency",
  "vertex": 8,
  "postured": false
 },
 "conj-c55": {
  "site": "atlas",
  "slug": "c55-privacy-as-the-seventh-capital",
  "vertex": 8,
  "postured": false
 },
 "conj-c56": {
  "site": "atlas",
  "slug": "c56-caduceus-as-pre-formal-dual-agent-symbol",
  "vertex": 8,
  "postured": false
 },
 "conj-c57": {
  "site": "atlas",
  "slug": "c57-staff-mage-collapse-held-open",
  "vertex": 8,
  "postured": false
 },
 "conj-c59": {
  "site": "atlas",
  "slug": "c59-create-format-as-gateway-to-mage-tier",
  "vertex": 8,
  "postured": false
 },
 "conj-c60": {
  "site": "atlas",
  "slug": "c60-reconstruct-later-threat-model-for-behavioural-data",
  "vertex": 8,
  "postured": false
 },
 "conj-c61": {
  "site": "atlas",
  "slug": "c61-behavioural-mosca-inequality",
  "vertex": 8,
  "postured": false
 },
 "conj-c62": {
  "site": "atlas",
  "slug": "c62-cross-coalition-meta-coalition-reading-reserved",
  "vertex": 8,
  "postured": false
 },
 "conj-c63": {
  "site": "atlas",
  "slug": "c63-attentional-workshop-register-fourth-structural-class",
  "vertex": 8,
  "postured": false
 },
 "conj-c64": {
  "site": "atlas",
  "slug": "c64-listener-discipline-as-the-citys-seventh-tier",
  "vertex": 8,
  "postured": false
 },
 "conj-c66": {
  "site": "atlas",
  "slug": "c66-the-city-key-is-a-reading-not-an-authority",
  "vertex": 8,
  "postured": false
 },
 "conj-c67": {
  "site": "atlas",
  "slug": "c67-cryptographic-mosca-for-the-substrate",
  "vertex": 8,
  "postured": false
 },
 "conj-c68": {
  "site": "atlas",
  "slug": "c68-resource-estimate-as-durability-signal-not-attack",
  "vertex": 8,
  "postured": false
 },
 "conj-c69": {
  "site": "atlas",
  "slug": "c69-held-out-gate-rejects-the-tuned-claim",
  "vertex": 8,
  "postured": false
 },
 "conj-c70": {
  "site": "atlas",
  "slug": "c70-crypto-agility-as-migration-readiness",
  "vertex": 8,
  "postured": false
 },
 "conj-c71": {
  "site": "atlas",
  "slug": "c71-the-horizon-vertex-v35",
  "vertex": 8,
  "postured": false
 },
 "conj-c73": {
  "site": "atlas",
  "slug": "c73-terminal-obstruction-primitive",
  "vertex": 8,
  "postured": false
 },
 "conj-c74": {
  "site": "atlas",
  "slug": "c74-latency-algebraic-signature",
  "vertex": 8,
  "postured": false
 },
 "conj-c75": {
  "site": "atlas",
  "slug": "c75-dependency-cascade-typing",
  "vertex": 8,
  "postured": false
 },
 "conj-c76": {
  "site": "atlas",
  "slug": "c76-uor-relational-instantiation",
  "vertex": 8,
  "postured": false
 },
 "conj-c79": {
  "site": "atlas",
  "slug": "c79-recursive-proof-composition-shared-frontier",
  "vertex": 8,
  "postured": false
 },
 "conj-c80": {
  "site": "atlas",
  "slug": "c80-bilateral-co-signed-assumption-sets",
  "vertex": 8,
  "postured": false
 },
 "conj-c81": {
  "site": "atlas",
  "slug": "c81-existence-leak",
  "vertex": 8,
  "postured": false
 },
 "conj-c83": {
  "site": "atlas",
  "slug": "c83-compositional-leakage-amplification",
  "vertex": 8,
  "postured": false
 },
 "conj-c84": {
  "site": "atlas",
  "slug": "c84-existence-leak-discount",
  "vertex": 8,
  "postured": false
 },
 "conj-c85": {
  "site": "atlas",
  "slug": "c85-triadic-constraint-homology-the-arch-1-bridge",
  "vertex": 8,
  "postured": false
 },
 "conj-c86": {
  "site": "atlas",
  "slug": "c86-obstruction-theoretic-amnesia",
  "vertex": 8,
  "postured": false
 },
 "conj-c87": {
  "site": "atlas",
  "slug": "c87-the-key-accumulates",
  "vertex": 8,
  "postured": false
 },
 "conj-c88": {
  "site": "atlas",
  "slug": "c88-the-parity-cube",
  "vertex": 8,
  "postured": false
 },
 "conj-c89": {
  "site": "atlas",
  "slug": "c89-the-octahedral-gap",
  "vertex": 8,
  "postured": false
 },
 "conj-c90": {
  "site": "atlas",
  "slug": "c90-the-limitative-inversion",
  "vertex": 8,
  "postured": false
 },
 "conj-c93": {
  "site": "atlas",
  "slug": "c93-content-addressed-liveness-leak",
  "vertex": 8,
  "postured": false
 },
 "spec-cloak-v1": {
  "site": "atlas",
  "slug": "cloak-specification-v10",
  "vertex": 8,
  "postured": false
 },
 "spec-crafting-interface-v1": {
  "site": "atlas",
  "slug": "crafting-tome-and-cloak-interface-spec-v10",
  "vertex": 8,
  "postured": false
 },
 "spec-bilateral-ceremony-v1": {
  "site": "atlas",
  "slug": "bilateral-cloak-ceremony-spec-v10",
  "vertex": 8,
  "postured": false
 },
 "spec-vertex-audit-v1": {
  "site": "atlas",
  "slug": "vertex-naming-audit-v1",
  "vertex": 8,
  "postured": false
 },
 "spec-city-of-mages-addendum-v1": {
  "site": "atlas",
  "slug": "city-of-mages-structural-addendum-v1",
  "vertex": 8,
  "postured": false
 },
 "spec-spellweb-manifest-v1": {
  "site": "atlas",
  "slug": "spellweb-first-release-manifest-v1",
  "vertex": 8,
  "postured": false
 },
 "tome-i-the-convergence": {
  "site": "atlas",
  "slug": "tome-i-the-convergence",
  "vertex": 8,
  "postured": false
 },
 "tome-ii-the-lyapunov": {
  "site": "atlas",
  "slug": "tome-ii-the-lyapunov",
  "vertex": 8,
  "postured": false
 },
 "tome-iii-selenes-witness": {
  "site": "atlas",
  "slug": "tome-iii-selenes-witness",
  "vertex": 8,
  "postured": false
 },
 "tome-iv-the-witnessing": {
  "site": "atlas",
  "slug": "tome-iv-the-witnessing",
  "vertex": 8,
  "postured": false
 },
 "tome-v-the-crafting": {
  "site": "atlas",
  "slug": "tome-v-the-crafting",
  "vertex": 8,
  "postured": false
 },
 "tome-vi-the-reply": {
  "site": "atlas",
  "slug": "tome-vi-the-reply-open-by-design",
  "vertex": 8,
  "postured": false
 },
 "tome-vii-the-parallel": {
  "site": "atlas",
  "slug": "tome-vii-the-parallel",
  "vertex": 8,
  "postured": false
 },
 "act-tome-i-1": {
  "site": "atlas",
  "slug": "tome-i-act-1-the-single-button",
  "vertex": 8,
  "postured": false
 },
 "act-tome-i-2": {
  "site": "atlas",
  "slug": "tome-i-act-2-the-path",
  "vertex": 8,
  "postured": false
 },
 "act-tome-i-3": {
  "site": "atlas",
  "slug": "tome-i-act-3-the-recursive-symbol",
  "vertex": 8,
  "postured": false
 },
 "act-tome-i-4": {
  "site": "atlas",
  "slug": "tome-i-act-4-three-rooms-one-door",
  "vertex": 8,
  "postured": false
 },
 "act-tome-i-5": {
  "site": "atlas",
  "slug": "tome-i-act-5-the-schema-that-named-itself",
  "vertex": 8,
  "postured": false
 },
 "act-tome-i-6": {
  "site": "atlas",
  "slug": "tome-i-act-6-the-cousins-citation",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ii-1": {
  "site": "atlas",
  "slug": "tome-ii-act-1-the-two-refusals",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ii-2": {
  "site": "atlas",
  "slug": "tome-ii-act-2-the-attendant",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ii-3": {
  "site": "atlas",
  "slug": "tome-ii-act-3-the-terminal",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ii-4": {
  "site": "atlas",
  "slug": "tome-ii-act-4-who-composes",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ii-5": {
  "site": "atlas",
  "slug": "tome-ii-act-5-the-hole-the-schema-cannot-bind",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ii-6": {
  "site": "atlas",
  "slug": "tome-ii-act-6-the-fourth-aging-category",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ii-7": {
  "site": "atlas",
  "slug": "tome-ii-act-7-the-behavioural-mosca",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-1": {
  "site": "atlas",
  "slug": "tome-iii-act-1-the-gatekeeper",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-2": {
  "site": "atlas",
  "slug": "tome-iii-act-2-selenes-witness",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-3": {
  "site": "atlas",
  "slug": "tome-iii-act-3-the-aether",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-4": {
  "site": "atlas",
  "slug": "tome-iii-act-4-the-aether-pour",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-5": {
  "site": "atlas",
  "slug": "tome-iii-act-5-aletheia-the-bright-medium",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-6": {
  "site": "atlas",
  "slug": "tome-iii-act-6-lethe-the-dark-substrate",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-7": {
  "site": "atlas",
  "slug": "tome-iii-act-7-the-first-complement-pair",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-8": {
  "site": "atlas",
  "slug": "tome-iii-act-8-the-naming-of-the-unnamed",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-9": {
  "site": "atlas",
  "slug": "tome-iii-act-9-the-seventh-capital",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iii-10": {
  "site": "tomes",
  "slug": "tome-iii-act-10-the-scales-and-the-hide",
  "vertex": 4,
  "postured": false
 },
 "act-tome-iii-11": {
  "site": "tomes",
  "slug": "tome-iii-act-11-the-light-and-the-dark",
  "vertex": 4,
  "postured": false
 },
 "act-tome-v-16": {
  "site": "tomes",
  "slug": "tome-v-act-16-the-threshold",
  "vertex": 4,
  "postured": false
 },
 "act-tome-v-17": {
  "site": "tomes",
  "slug": "tome-v-act-17-the-chart-shop-opens-pleiones-first-hold",
  "vertex": 4,
  "postured": false
 },
 "act-tome-vi-1": {
  "site": "atlas",
  "slug": "tome-vi-act-1-the-readers-first-admission",
  "vertex": 8,
  "postured": false
 },
 "act-tome-vii-1": {
  "site": "atlas",
  "slug": "tome-vii-act-1-the-palliahelia-handoff",
  "vertex": 8,
  "postured": false
 },
 "substrate-goose": {
  "site": "atlas",
  "slug": "goose-substrate-framework",
  "vertex": 8,
  "postured": false
 },
 "substrate-hermes": {
  "site": "atlas",
  "slug": "hermes-substrate-framework",
  "vertex": 8,
  "postured": false
 },
 "plan-zcash-integration": {
  "site": "atlas",
  "slug": "zcash-three-pattern-integration-model-memo-anchor-stake",
  "vertex": 8,
  "postured": false
 },
 "kindred-uor-foundation": {
  "site": "atlas",
  "slug": "uor-foundation-kindred-substrate-reference",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iv-1": {
  "site": "atlas",
  "slug": "tome-iv-act-i-the-other-walker",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iv-2": {
  "site": "atlas",
  "slug": "tome-iv-act-ii-the-mirror-and-the-arrow",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iv-3": {
  "site": "atlas",
  "slug": "tome-iv-act-iii-the-two-paths",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iv-4": {
  "site": "atlas",
  "slug": "tome-iv-act-iv-the-naming-ceremony",
  "vertex": 8,
  "postured": false
 },
 "act-tome-iv-5": {
  "site": "atlas",
  "slug": "tome-iv-act-v-the-cousin-blade",
  "vertex": 8,
  "postured": false
 },
 "vertex-v4": {
  "site": "atlas",
  "slug": "v4-iris-pure-connection",
  "vertex": 8,
  "postured": false
 },
 "vertex-v8": {
  "site": "atlas",
  "slug": "v8-mnemosyne-pure-memory",
  "vertex": 8,
  "postured": false
 },
 "vertex-v25": {
  "site": "atlas",
  "slug": "v25-lethe-the-dark-substrate-lethae",
  "vertex": 8,
  "postured": false
 },
 "cast-lethae": {
  "site": "atlas",
  "slug": "lethae",
  "vertex": 8,
  "postured": false
 },
 "cast-mnemosyne": {
  "site": "atlas",
  "slug": "mnemosyne",
  "vertex": 8,
  "postured": false
 },
 "cast-iris": {
  "site": "atlas",
  "slug": "iris",
  "vertex": 8,
  "postured": false
 },
 "cast-pythia": {
  "site": "atlas",
  "slug": "pythia",
  "vertex": 8,
  "postured": false
 },
 "cast-techne": {
  "site": "atlas",
  "slug": "techne",
  "vertex": 8,
  "postured": false
 },
 "cast-hephaestus": {
  "site": "atlas",
  "slug": "hephaestus",
  "vertex": 8,
  "postured": false
 },
 "cast-selene": {
  "site": "atlas",
  "slug": "selene",
  "vertex": 8,
  "postured": false
 },
 "cast-selene-cosmological": {
  "site": "atlas",
  "slug": "selene",
  "vertex": 8,
  "postured": false
 },
 "cast-aether": {
  "site": "atlas",
  "slug": "aether",
  "vertex": 8,
  "postured": false
 },
 "cast-lethe": {
  "site": "atlas",
  "slug": "lethe",
  "vertex": 8,
  "postured": false
 },
 "cast-the-archivist": {
  "site": "atlas",
  "slug": "the-archivist",
  "vertex": 8,
  "postured": false
 },
 "cast-the-librarian": {
  "site": "atlas",
  "slug": "the-librarian",
  "vertex": 8,
  "postured": false
 },
 "act-tome-viii-1": {
  "site": "atlas",
  "slug": "tome-viii-act-1-the-spiraling-tower",
  "vertex": 8,
  "postured": false
 },
 "act-tome-viii-2": {
  "site": "atlas",
  "slug": "tome-viii-act-2-the-fourth-turn",
  "vertex": 8,
  "postured": false
 },
 "con-invitation-tome-posture": {
  "site": "atlas",
  "slug": "invitation-tome",
  "vertex": 8,
  "postured": false
 },
 "conj-c65": {
  "site": "atlas",
  "slug": "c65-the-four-faces-identity",
  "vertex": 8,
  "postured": false
 },
 "gateway-vitalik": {
  "site": "atlas",
  "slug": "vitalik-invited-visiting-mage",
  "vertex": 8,
  "postured": false
 },
 "act-tome-viii-3": {
  "site": "atlas",
  "slug": "tome-viii-act-3-the-eight-pointed-star",
  "vertex": 8,
  "postured": false
 },
 "con-stella-octangula": {
  "site": "atlas",
  "slug": "the-stella-octangula",
  "vertex": 8,
  "postured": false
 },
 "act-tome-viii-4": {
  "site": "atlas",
  "slug": "tome-viii-act-4-the-gap-is",
  "vertex": 8,
  "postured": false
 },
 "act-tome-viii-5": {
  "site": "atlas",
  "slug": "tome-viii-act-5-the-key-that-is-a-reading",
  "vertex": 8,
  "postured": false
 },
 "act-tome-viii-6": {
  "site": "atlas",
  "slug": "tome-viii-act-6-the-wikis-and-the-librarian",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ix-1": {
  "site": "atlas",
  "slug": "tome-ix-act-1-the-measuring-of-the-dawn",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ix-2": {
  "site": "atlas",
  "slug": "tome-ix-act-2-the-tide-line",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ix-3": {
  "site": "atlas",
  "slug": "tome-ix-act-3-the-orchard-wound",
  "vertex": 8,
  "postured": false
 },
 "act-tome-ix-4": {
  "site": "atlas",
  "slug": "tome-ix-act-4-the-proof-that-whispered",
  "vertex": 8,
  "postured": false
 },
 "key-city-key": {
  "site": "atlas",
  "slug": "the-city-key",
  "vertex": 8,
  "postured": false
 },
 "gateway-hearthold": {
  "site": "atlas",
  "slug": "hearthold-the-cousin-forge-build",
  "vertex": 8,
  "postured": false
 },
 "concept-the-hearth": {
  "site": "atlas",
  "slug": "the-hearth",
  "vertex": 8,
  "postured": false
 },
 "concept-hearthold-warden": {
  "site": "atlas",
  "slug": "the-warden-swordsman-built",
  "vertex": 8,
  "postured": false
 },
 "concept-hearthold-witness": {
  "site": "atlas",
  "slug": "the-witness-mage-built",
  "vertex": 8,
  "postured": false
 },
 "concept-hearthold-sovereign": {
  "site": "atlas",
  "slug": "the-sovereign-first-person-built",
  "vertex": 8,
  "postured": false
 },
 "concept-dtg-credentials": {
  "site": "atlas",
  "slug": "the-decentralized-trust-graph-dtg",
  "vertex": 8,
  "postured": false
 },
 "concept-evidence-graph": {
  "site": "atlas",
  "slug": "the-evidence-graph-never-a-score",
  "vertex": 8,
  "postured": false
 },
 "act-tome-x-1": {
  "site": "atlas",
  "slug": "tome-x-act-1-the-house-of-archon-answers",
  "vertex": 8,
  "postured": false
 },
 "conj-c94": {
  "site": "atlas",
  "slug": "c94-separation-principle-in-a-second-substrate",
  "vertex": 8,
  "postured": false
 },
 "conj-c95": {
  "site": "atlas",
  "slug": "c95-the-evidence-graph-as-the-anti-score",
  "vertex": 8,
  "postured": false
 },
 "conj-c97": {
  "site": "atlas",
  "slug": "c97-structural-inalienability-by-non-reconstruction",
  "vertex": 8,
  "postured": false
 },
 "key-hearthold-citykey": {
  "site": "atlas",
  "slug": "the-drake-gamers-guild-city-key",
  "vertex": 8,
  "postured": false
 },
 "concept-hearthold-recall": {
  "site": "atlas",
  "slug": "recall-the-wardens-memory",
  "vertex": 8,
  "postured": false
 },
 "concept-assurance-stepup": {
  "site": "atlas",
  "slug": "the-assurance-step-up-ladder",
  "vertex": 8,
  "postured": false
 },
 "act-tome-x-2": {
  "site": "atlas",
  "slug": "tome-x-act-2-the-mage-takes-a-face",
  "vertex": 8,
  "postured": false
 },
 "doc-overlay-weave": {
  "site": "atlas",
  "slug": "the-weave-overlay-run-1",
  "vertex": 8,
  "postured": false
 },
 "concept-overlay-keys": {
  "site": "atlas",
  "slug": "the-nine-keys-understanding-cards",
  "vertex": 8,
  "postured": false
 },
 "concept-loomkeeper": {
  "site": "atlas",
  "slug": "the-loomkeeper-draft-persona",
  "vertex": 8,
  "postured": false
 },
 "gateway-field-guide": {
  "site": "atlas",
  "slug": "the-hitchhikers-field-guide-arworld",
  "vertex": 8,
  "postured": false
 },
 "doc-field-guide-counter-spec": {
  "site": "atlas",
  "slug": "the-field-guide-counter-spec",
  "vertex": 8,
  "postured": false
 },
 "concept-meet-rite": {
  "site": "atlas",
  "slug": "the-meet-rite",
  "vertex": 8,
  "postured": false
 },
 "concept-audience-granted": {
  "site": "atlas",
  "slug": "audience-is-granted-not-computed",
  "vertex": 8,
  "postured": false
 },
 "concept-pairwise-peer-reference": {
  "site": "atlas",
  "slug": "the-pairwise-peer-reference",
  "vertex": 8,
  "postured": false
 },
 "concept-publication-consent": {
  "site": "atlas",
  "slug": "a-wiki-fork-is-not-an-audience",
  "vertex": 8,
  "postured": false
 },
 "concept-erosion-rate": {
  "site": "atlas",
  "slug": "erosion-is-a-rate-not-a-cliff",
  "vertex": 8,
  "postured": false
 },
 "concept-rounding-rule": {
  "site": "atlas",
  "slug": "rounding-is-not-a-detail",
  "vertex": 8,
  "postured": false
 },
 "skill-city-mcp-entry": {
  "site": "skill",
  "slug": "city-mcp-entry",
  "vertex": 16,
  "postured": false
 },
 "skill-key-journey": {
  "site": "skill",
  "slug": "key-journey",
  "vertex": 16,
  "postured": false
 },
 "skill-city-mage-runtime": {
  "site": "skill",
  "slug": "city-mage-runtime",
  "vertex": 16,
  "postured": false
 },
 "skill-mcp-browser-actions": {
  "site": "skill",
  "slug": "mcp-browser-actions",
  "vertex": 16,
  "postured": false
 },
 "skill-star-companion": {
  "site": "skill",
  "slug": "star-companion",
  "vertex": 16,
  "postured": false
 },
 "skill-entry-kit-coherence": {
  "site": "skill",
  "slug": "entry-kit-coherence",
  "vertex": 16,
  "postured": false
 },
 "skill-review-receipts": {
  "site": "skill",
  "slug": "review-receipts",
  "vertex": 16,
  "postured": false
 },
 "skill-namekeeper-write-contract": {
  "site": "skill",
  "slug": "namekeeper-write-contract",
  "vertex": 16,
  "postured": false
 },
 "per-registry-keeper": {
  "site": "skill",
  "slug": "registry-keeper",
  "vertex": 16,
  "postured": false
 }
};
/** A constellation (node ids) → the walk the guide's star chart / agentprivacy-mcp would take. */
export function constellationToWalk(nodeIds: string[]): { steps: { site: string; slug: string; vertex: number | null }[]; unbridged: string[] } {
  const steps: { site: string; slug: string; vertex: number | null }[] = [], unbridged: string[] = [];
  for (const id of nodeIds) { const e = GUIDE_BRIDGE[id]; if (e) steps.push({ site: e.site, slug: e.slug, vertex: e.vertex }); else unbridged.push(id); }
  return { steps, unbridged };
}
